/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.array-user.conf,v 5.26 2005/04/26 22:13:28 rstory Exp $
 *
 * $Id:$
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#ifndef RADIUSACCSERVEREXTTABLE_H
#define RADIUSACCSERVEREXTTABLE_H

#include "dm_token.h"
#include "dm_store.h"

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/library/container.h>
#include <net-snmp/agent/table_array.h>

/** Index radiusAccServerExtIndex is internal */

typedef struct radiusAccServerExtTable_context_s {
	netsnmp_index   index;                         /** THIS MUST BE FIRST!!! */
	
	long            radiusAccServerExtIndex;       /** INTEGER32 = ASN_INTEGER */
	unsigned long   radiusAccClientCounterDiscontinuity;
	oid             oid[1];

	struct dm_value_table *client;
} radiusAccServerExtTable_context;

#define radiusAccServerExtTable_TABLE_OID 1,3,6,1,2,1,67,2,2,1,1,4

/*************************************************************
 * column number definitions for table radiusAccServerExtTable
 */
#define COLUMN_RADIUSACCSERVEREXTINDEX 1
#define COLUMN_RADIUSACCSERVERINETADDRESSTYPE 2
#define COLUMN_RADIUSACCSERVERINETADDRESS 3
#define COLUMN_RADIUSACCCLIENTSERVERINETPORTNUMBER 4
#define COLUMN_RADIUSACCCLIENTEXTROUNDTRIPTIME 5
#define COLUMN_RADIUSACCCLIENTEXTREQUESTS 6
#define COLUMN_RADIUSACCCLIENTEXTRETRANSMISSIONS 7
#define COLUMN_RADIUSACCCLIENTEXTRESPONSES 8
#define COLUMN_RADIUSACCCLIENTEXTMALFORMEDRESPONSES 9
#define COLUMN_RADIUSACCCLIENTEXTBADAUTHENTICATORS 10
#define COLUMN_RADIUSACCCLIENTEXTPENDINGREQUESTS 11
#define COLUMN_RADIUSACCCLIENTEXTTIMEOUTS 12
#define COLUMN_RADIUSACCCLIENTEXTUNKNOWNTYPES 13
#define COLUMN_RADIUSACCCLIENTEXTPACKETSDROPPED 14
#define COLUMN_RADIUSACCCLIENTCOUNTERDISCONTINUITY 15
#define radiusAccServerExtTable_COL_MIN 2
#define radiusAccServerExtTable_COL_MAX 15

void init_radiusAccServerExtTable(void);
void add_radiusAccServerExtTable(dm_id id, struct dm_value_table *client);
void del_radiusAccServerExtTable(dm_id id);

#endif /** RADIUSACCSERVEREXTTABLE_H */
