/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.array-user.conf,v 5.26 2005/04/26 22:13:28 rstory Exp $
 *
 * $Id:$
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#ifndef RADIUSAUTHCLIENTEXTTABLE_H
#define RADIUSAUTHCLIENTEXTTABLE_H

#include "tr069_token.h"
#include "tr069_store.h"

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/library/container.h>
#include <net-snmp/agent/table_array.h>

/** Index radiusAuthClientExtIndex is internal */

typedef struct radiusAuthClientExtTable_context_s {
	netsnmp_index   index;                           /** THIS MUST BE FIRST!!! */
	
	long            radiusAuthClientExtIndex;        /** INTEGER32 = ASN_INTEGER */
	unsigned long   radiusAuthServCounterDiscontinuity;
	oid             oid[1];

	struct tr069_value_table *client;
} radiusAuthClientExtTable_context;

#define radiusAuthClientExtTable_TABLE_OID 1,3,6,1,2,1,67,1,1,1,1,16

/*************************************************************
 * column number definitions for table radiusAuthClientExtTable
 */
#define COLUMN_RADIUSAUTHCLIENTEXTINDEX 1
#define COLUMN_RADIUSAUTHCLIENTINETADDRESSTYPE 2
#define COLUMN_RADIUSAUTHCLIENTINETADDRESS 3
#define COLUMN_RADIUSAUTHCLIENTEXTID 4
#define COLUMN_RADIUSAUTHSERVEXTACCESSREQUESTS 5
#define COLUMN_RADIUSAUTHSERVEXTDUPACCESSREQUESTS 6
#define COLUMN_RADIUSAUTHSERVEXTACCESSACCEPTS 7
#define COLUMN_RADIUSAUTHSERVEXTACCESSREJECTS 8
#define COLUMN_RADIUSAUTHSERVEXTACCESSCHALLENGES 9
#define COLUMN_RADIUSAUTHSERVEXTMALFORMEDACCESSREQUESTS 10
#define COLUMN_RADIUSAUTHSERVEXTBADAUTHENTICATORS 11
#define COLUMN_RADIUSAUTHSERVEXTPACKETSDROPPED 12
#define COLUMN_RADIUSAUTHSERVEXTUNKNOWNTYPES 13
#define COLUMN_RADIUSAUTHSERVCOUNTERDISCONTINUITY 14
#define radiusAuthClientExtTable_COL_MIN 2
#define radiusAuthClientExtTable_COL_MAX 14

void init_radiusAuthClientExtTable(void);
void add_radiusAuthClientExtTable(tr069_id id, struct tr069_value_table *client);
void del_radiusAuthClientExtTable(tr069_id id);

#endif /** RADIUSAUTHCLIENTEXTTABLE_H */
