/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef RADIUSACCTSERV_H
#define RADIUSACCTSERV_H

/* function declarations */
void init_radiusAccServ(void);

#endif /* RADIUSACCTSERV_H */
