/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef RADIUSAUTHCLIENT_H
#define RADIUSAUTHCLIENT_H

/* function declarations */
void init_radiusAuthClient(void);

#endif /* RADIUSAUTHCLIENT_H */
