mand-1.0: libdmconfig/debug.h File Reference
debug.h File Reference
#include "diammsg.h"
Functions
void dump_diam_packet (DIAM_REQUEST *req)
Function Documentation
void dump_diam_packet (DIAM_REQUEST * req)
Definition at line 245 of file debug.c.
References _get_avp(), _get_cmd(), diam_packet::app_id, AVP_CONTAINER, code, diam_decode_avpgrp(), diam_packet_code(), diam_packet_length(), diam_request_get_avp(), diam_request_reset_avp(), dump_avpgrp(), diam_packet::end2end_id, diam_packet::flags, flags, hexdump(), diam_packet::hop2hop_id, diam_request::packet, packet, vendor_id, and diam_packet::version.
Referenced by dm_generic_register_request(), and readEvent().