mand-1.0: libdmconfig/debug.c File Reference
debug.c File Reference
#include <stdio.h>
#include <stdarg.h>
#include <stdint.h>
#include <string.h>
#include <inttypes.h>
#include <arpa/inet.h>
#include <talloc.h>
#include "errors.h"
#include "diammsg.h"
#include "codes.h"
#include "debug.h"
Data Structures
struct code2str
Macros
#define initC2S(x)
Functions
static int comp_code (const void *m1, const void *m2)
const char * _get_cmd (uint16_t code)
const char * _get_avp (uint16_t code)
static void init_code2str (void)
static void hexdump (void *data, int len)
static const char * indent (int level)
static void dump_avpgrp (int level, DIAM_AVPGRP *avpgrp)
void dump_diam_packet (DIAM_REQUEST *req)
Variables
static struct code2str cmd2str []
static struct code2str avp2str []
static const char * unk_code
static const char * unk_avp
Macro Definition Documentation
#define initC2S (x)
Definition at line 33 of file debug.c.
Function Documentation
const char* _get_avp (uint16_t code)
Definition at line 180 of file debug.c.
References code2str::code, code2str::command, comp_code(), and unk_avp.
Referenced by dump_avpgrp(), and dump_diam_packet().
const char* _get_cmd (uint16_t code)
Definition at line 168 of file debug.c.
References code2str::code, code2str::command, comp_code(), and unk_code.
Referenced by dump_diam_packet().
static int comp_code (const void * m1, const void * m2) static
Definition at line 152 of file debug.c.
References code2str::code.
Referenced by _get_avp(), _get_cmd(), and init_code2str().
static void dump_avpgrp (int level, DIAM_AVPGRP * avpgrp) static
Definition at line 224 of file debug.c.
References _get_avp(), AVP_CONTAINER, code, diam_avpgrp_get_avp(), diam_decode_avpgrp(), flags, indent(), and vendor_id.
Referenced by dump_diam_packet().
void dump_diam_packet (DIAM_REQUEST * req)
Definition at line 245 of file debug.c.
References _get_avp(), _get_cmd(), diam_packet::app_id, AVP_CONTAINER, code, diam_decode_avpgrp(), diam_packet_code(), diam_packet_length(), diam_request_get_avp(), diam_request_reset_avp(), dump_avpgrp(), diam_packet::end2end_id, diam_packet::flags, flags, hexdump(), diam_packet::hop2hop_id, diam_request::packet, packet, vendor_id, and diam_packet::version.
Referenced by dm_generic_register_request(), and readEvent().
static void hexdump (void * data, int len) static
Definition at line 204 of file debug.c.
Referenced by dump_diam_packet().
static const char* indent (int level) static
Definition at line 214 of file debug.c.
Referenced by dump_avpgrp().
static void init_code2str (void) static
Definition at line 193 of file debug.c.
References comp_code().
Variable Documentation
struct code2str avp2str[] static
Definition at line 92 of file debug.c.
struct code2str cmd2str[] static
Definition at line 35 of file debug.c.
const char* unk_avp static
Definition at line 166 of file debug.c.
Referenced by _get_avp().
const char* unk_code static
Definition at line 165 of file debug.c.
Referenced by _get_cmd().