mand-1.0: libdmconfig/diammsg.h File Reference
diammsg.h File Reference
#include <arpa/inet.h>
#include <netinet/in.h>
#include <bits/byteswap.h>
#include <stdint.h>
#include <string.h>
Data Structures
struct diam_avp
struct diam_avpgrp_info
struct diam_avpgrp
struct diam_request_info
struct diam_packet
struct diam_request
struct diam_timeval
Macros
#define _GNU_SOURCE
#define IANA_INET
#define IANA_INET6
#define ntohll(x)
#define htonll(x)
#define DIAM_BLOCK_ALLOC
#define PAD32(x)
#define TIME_SINCE_EPOCH
#define CMD_FLAG_REQUEST
#define CMD_FLAG_PROXIABLE
#define CMD_FLAG_ERROR
#define CMD_FLAG_RETRANSMITED
#define CMD_FLAG_RESERVED
#define AVP_FLAG_VENDOR
#define AVP_FLAG_MANDATORY
#define AVP_FLAG_PRIVAT
#define AVP_FLAG_RESERVED
Typedefs
typedef struct diam_request DIAM_REQUEST
typedef struct diam_avp DIAM_AVP
typedef struct diam_avpgrp_info DIAM_AVPGRP_INFO
typedef struct diam_avpgrp DIAM_AVPGRP
typedef struct diam_request_info DIAM_REQUEST_INFO
typedef struct diam_packet DIAM_PACKET
typedef struct diam_request_head DIAM_REQUEST_HEAD
typedef struct diam_timeval DIAM_TIMEVAL
Functions
struct diam_avp __attribute__ ((packed))
int get_avp (uint32_t *code, uint8_t *flags, uint32_t *vendor_id, void **data, size_t *len, DIAM_AVP **src)
DIAM_REQUEST * new_diam_request (void *ctx, uint32_t code, uint8_t flags, uint32_t appid, uint32_t hopid, uint32_t endid)
int diam_decode_request (void *ctx, DIAM_REQUEST **req, void *data, size_t len)
start decoding a request received from the network minimum lenght of received data if 4 bytes
int diam_add_data (DIAM_REQUEST *req, void *data, size_t len)
int diam_decode_complete (DIAM_REQUEST *req)
int build_diam_request (void *ctx, DIAM_REQUEST **req, DIAM_AVPGRP *avpgrp)
DIAM_AVPGRP * new_diam_avpgrp (void *ctx)
DIAM_AVPGRP * diam_decode_avpgrp (void *ctx, void *data, size_t len)
int diam_avpgrp_add_avpgrp (void *ctx, DIAM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, DIAM_AVPGRP *source)
int diam_avpgrp_insert_raw (void *ctx, DIAM_AVPGRP **avpgrp, const void *data, size_t len)
int diam_avpgrp_add_raw (void *ctx, DIAM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, const void *data, size_t len)
int diam_avpgrp_add_address (void *ctx, DIAM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int af, const void *data)
int diam_avpgrp_add_uint32_string (void *ctx, DIAM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint32_t d1, const char *d2)
int diam_get_address_avp (int *af, void *addr, const void *src)
static uint32_t uint24to32 (uint8_t i24[3])
static void uint32to24 (uint8_t i24[3], uint32_t i32)
static uint8_t diam_packet_flags (DIAM_PACKET *pkt)
static uint32_t diam_packet_length (DIAM_PACKET *pkt)
static uint32_t diam_packet_code (DIAM_PACKET *pkt)
static uint32_t diam_app_id (DIAM_PACKET *pkt)
static uint32_t diam_end2end_id (DIAM_PACKET *pkt)
static uint32_t diam_hop2hop_id (DIAM_PACKET *pkt)
static uint32_t diam_avp_length (DIAM_AVP *avp)
static void diam_request_reset_avp (DIAM_REQUEST *req)
static int diam_request_get_avp (DIAM_REQUEST *req, uint32_t *code, uint8_t *flags, uint32_t *vendor_id, void **data, size_t *len)
static void diam_avpgrp_reset_avp (DIAM_AVPGRP *avpgrp)
static int diam_avpgrp_get_avp (DIAM_AVPGRP *avpgrp, uint32_t *code, uint8_t *flags, uint32_t *vendor_id, void **data, size_t *len)
static int diam_avpgrp_add_string (void *ctx, DIAM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, const char *data)
static int diam_avpgrp_add_int8 (void *ctx, DIAM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int8_t data)
static int diam_avpgrp_add_uint8 (void *ctx, DIAM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint8_t data)
static int diam_avpgrp_add_int16 (void *ctx, DIAM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int16_t data)
static int diam_avpgrp_add_uint16 (void *ctx, DIAM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint16_t data)
static int diam_avpgrp_add_int32 (void *ctx, DIAM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int32_t data)
static int diam_avpgrp_add_uint32 (void *ctx, DIAM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint32_t data)
static int diam_avpgrp_add_uint64 (void *ctx, DIAM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint64_t data)
static int diam_avpgrp_add_int64 (void *ctx, DIAM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int64_t data)
static int diam_avpgrp_add_float32 (void *ctx, DIAM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, float data)
static int diam_avpgrp_add_float64 (void *ctx, DIAM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, double data)
static int diam_avpgrp_add_time (void *ctx, DIAM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, time_t data)
static int diam_avpgrp_add_timeval (void *ctx, DIAM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, struct timeval value)
static int diam_avpgrp_insert_avpgrp (void *ctx, DIAM_AVPGRP **avpgrp, DIAM_AVPGRP *source)
static int diam_get_string_avp (char *dest, size_t dlen, const void *src, size_t slen)
static int8_t diam_get_int8_avp (const void *src)
static uint8_t diam_get_uint8_avp (const void *src)
static int16_t diam_get_int16_avp (const void *src)
static uint16_t diam_get_uint16_avp (const void *src)
static int32_t diam_get_int32_avp (const void *src)
static uint32_t diam_get_uint32_avp (const void *src)
static int64_t diam_get_int64_avp (const void *src)
static uint64_t diam_get_uint64_avp (const void *src)
static time_t diam_get_time_avp (const void *src)
static struct timeval diam_get_timeval_avp (const void *src)
Variables
uint32_t code
uint8_t flags
uint8_t length [3]
uint32_t vendor_id
DIAM_AVP * avpptr
uint32_t size
uint32_t avps_length
DIAM_AVPGRP_INFO info
DIAM_REQUEST * next
uint8_t version
uint32_t app_id
uint32_t hop2hop_id
uint32_t end2end_id
DIAM_PACKET packet
uint32_t tv_sec
uint32_t tv_usec
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 17 of file diammsg.h.
#define AVP_FLAG_MANDATORY
Definition at line 115 of file diammsg.h.
Referenced by diam_avpgrp_add_avpgrp(), diam_avpgrp_add_raw(), and get_avp().
#define AVP_FLAG_PRIVAT
Definition at line 116 of file diammsg.h.
Referenced by diam_avpgrp_add_raw(), and get_avp().
#define AVP_FLAG_RESERVED
Definition at line 117 of file diammsg.h.
Referenced by get_avp().
#define AVP_FLAG_VENDOR
Definition at line 114 of file diammsg.h.
Referenced by diam_avpgrp_add_raw(), and get_avp().
#define CMD_FLAG_ERROR
Definition at line 108 of file diammsg.h.
#define CMD_FLAG_PROXIABLE
Definition at line 107 of file diammsg.h.
#define CMD_FLAG_REQUEST
Definition at line 106 of file diammsg.h.
Referenced by dm_generic_register_request(), and readEvent().
#define CMD_FLAG_RESERVED
Definition at line 110 of file diammsg.h.
#define CMD_FLAG_RETRANSMITED
Definition at line 109 of file diammsg.h.
#define DIAM_BLOCK_ALLOC
Definition at line 41 of file diammsg.h.
Referenced by diam_avpgrp_add_raw(), diam_avpgrp_insert_raw(), and new_diam_avpgrp().
#define htonll (x)
Definition at line 33 of file diammsg.h.
Referenced by diam_avpgrp_add_int64(), diam_avpgrp_add_uint64(), dm_grp_set_absticks(), dm_grp_set_int64(), dm_grp_set_relticks(), dm_grp_set_uint64(), and Lua_encode_value().
#define IANA_INET
Definition at line 26 of file diammsg.h.
Referenced by diam_avpgrp_add_address(), and diam_get_address_avp().
#define IANA_INET6
Definition at line 27 of file diammsg.h.
Referenced by diam_avpgrp_add_address(), and diam_get_address_avp().
#define ntohll (x)
Definition at line 32 of file diammsg.h.
Referenced by diam_get_int64_avp(), and diam_get_uint64_avp().
#define PAD32 (x)
Definition at line 43 of file diammsg.h.
Referenced by diam_avpgrp_add_avpgrp(), diam_avpgrp_add_raw(), and get_avp().
#define TIME_SINCE_EPOCH
Definition at line 45 of file diammsg.h.
Referenced by diam_avpgrp_add_time(), and diam_get_time_avp().
Typedef Documentation
typedef struct diam_avp DIAM_AVP
Definition at line 49 of file diammsg.h.
typedef struct diam_avpgrp DIAM_AVPGRP
Definition at line 51 of file diammsg.h.
typedef struct diam_avpgrp_info DIAM_AVPGRP_INFO
Definition at line 50 of file diammsg.h.
typedef struct diam_packet DIAM_PACKET
Definition at line 53 of file diammsg.h.
typedef struct diam_request DIAM_REQUEST
Definition at line 48 of file diammsg.h.
typedef struct diam_request_head DIAM_REQUEST_HEAD
Definition at line 54 of file diammsg.h.
typedef struct diam_request_info DIAM_REQUEST_INFO
Definition at line 52 of file diammsg.h.
typedef struct diam_timeval DIAM_TIMEVAL
Definition at line 55 of file diammsg.h.
Function Documentation
struct diam_timeval __attribute__ ((packed))
Referenced by diam_avpgrp_add_address().
int build_diam_request (void * ctx, DIAM_REQUEST ** req, DIAM_AVPGRP * avpgrp)
Definition at line 149 of file diammsg.c.
References diam_avpgrp_info::avps_length, diam_avpgrp::info, diam_request::info, diam_request_info::size, and uint32to24().
Referenced by dm_generic_register_request().
int diam_add_data (DIAM_REQUEST * req, void * data, size_t len)
Definition at line 121 of file diammsg.c.
References diam_request_info::avpptr, diam_packet_length(), diam_request::info, diam_request::packet, and diam_request_info::size.
static uint32_t diam_app_id (DIAM_PACKET * pkt) inline static
Definition at line 237 of file diammsg.h.
References diam_packet::app_id.
static uint32_t diam_avp_length (DIAM_AVP * avp) inline static
Definition at line 252 of file diammsg.h.
References diam_avp::length, and uint24to32().
Referenced by diam_avpgrp_add_avpgrp(), and get_avp().
int diam_avpgrp_add_address (void * ctx, DIAM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int af, const void * data)
Definition at line 267 of file diammsg.c.
References __attribute__(), diam_avpgrp_add_raw(), IANA_INET, and IANA_INET6.
Referenced by dm_generic_register_request_char_address(), dm_generic_send_request_char_address_get_char(), and dm_grp_set_addr().
int diam_avpgrp_add_avpgrp (void * ctx, DIAM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, DIAM_AVPGRP * source)
Definition at line 196 of file diammsg.c.
References AVP_FLAG_MANDATORY, diam_avpgrp_info::avps_length, diam_avp_length(), diam_avpgrp_add_raw(), diam_avpgrp::info, and PAD32.
Referenced by dm_generic_register_request(), dm_generic_register_request_bool_grp(), dm_generic_send_request_bool_grp(), dm_grp_set(), and dm_grp_set_addr().
static int diam_avpgrp_add_float32 (void * ctx, DIAM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, float data) inline static
Definition at line 360 of file diammsg.h.
References diam_avpgrp_add_raw().
static int diam_avpgrp_add_float64 (void * ctx, DIAM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, double data) inline static
Definition at line 367 of file diammsg.h.
References diam_avpgrp_add_raw().
static int diam_avpgrp_add_int16 (void * ctx, DIAM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int16_t data) inline static
Definition at line 306 of file diammsg.h.
static int diam_avpgrp_add_int32 (void * ctx, DIAM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int32_t data) inline static
Definition at line 324 of file diammsg.h.
References diam_avpgrp_add_raw().
static int diam_avpgrp_add_int64 (void * ctx, DIAM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int64_t data) inline static
Definition at line 351 of file diammsg.h.
References diam_avpgrp_add_raw(), and htonll.
static int diam_avpgrp_add_int8 (void * ctx, DIAM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int8_t data) inline static
Definition at line 292 of file diammsg.h.
References diam_avpgrp_add_raw().
int diam_avpgrp_add_raw (void * ctx, DIAM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, const void * data, size_t len)
Definition at line 229 of file diammsg.c.
References AVP_FLAG_MANDATORY, AVP_FLAG_PRIVAT, AVP_FLAG_VENDOR, diam_avpgrp_info::avps_length, diam_avp::code, DIAM_BLOCK_ALLOC, diam_avp::flags, diam_avpgrp::info, diam_avp::length, PAD32, diam_avpgrp_info::size, uint32to24(), and diam_avp::vendor_id.
Referenced by diam_avpgrp_add_address(), diam_avpgrp_add_avpgrp(), diam_avpgrp_add_float32(), diam_avpgrp_add_float64(), diam_avpgrp_add_int32(), diam_avpgrp_add_int64(), diam_avpgrp_add_int8(), diam_avpgrp_add_string(), diam_avpgrp_add_time(), diam_avpgrp_add_timeval(), diam_avpgrp_add_uint32(), diam_avpgrp_add_uint32_string(), diam_avpgrp_add_uint64(), diam_avpgrp_add_uint8(), and dm_grp_set().
static int diam_avpgrp_add_string (void * ctx, DIAM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, const char * data) inline static
Definition at line 285 of file diammsg.h.
References diam_avpgrp_add_raw().
Referenced by dm_generic_register_request_char_address(), dm_generic_register_request_path(), dm_generic_register_request_string(), dm_generic_send_request_char_address_get_char(), dm_generic_send_request_path_get_grp(), dm_generic_send_request_string(), dm_grp_param_notify(), dm_grp_set(), dm_grp_set_addr(), dm_register_add_instance(), dm_register_find_instance(), dm_register_list(), dm_register_recursive_param_notify(), dm_send_add_instance(), dm_send_find_instance(), dm_send_list(), and dm_send_recursive_param_notify().
static int diam_avpgrp_add_time (void * ctx, DIAM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, time_t data) inline static
Definition at line 374 of file diammsg.h.
References diam_avpgrp_add_raw(), and TIME_SINCE_EPOCH.
static int diam_avpgrp_add_timeval (void * ctx, DIAM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, struct timeval value) inline static
Definition at line 388 of file diammsg.h.
References diam_avpgrp_add_raw(), diam_timeval::tv_sec, and diam_timeval::tv_usec.
Referenced by dm_generic_register_request_uint32_timeouts(), and dm_generic_send_request_uint32_timeouts_get_grp().
static int diam_avpgrp_add_uint16 (void * ctx, DIAM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint16_t data) inline static
Definition at line 315 of file diammsg.h.
Referenced by dm_register_add_instance(), dm_register_list(), dm_send_add_instance(), and dm_send_list().
static int diam_avpgrp_add_uint32 (void * ctx, DIAM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint32_t data) inline static
Definition at line 333 of file diammsg.h.
References diam_avpgrp_add_raw().
Referenced by dm_generic_register_request(), dm_generic_register_request_uint32_timeouts(), and dm_generic_send_request_uint32_timeouts_get_grp().
int diam_avpgrp_add_uint32_string (void * ctx, DIAM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint32_t d1, const char * d2)
Definition at line 291 of file diammsg.c.
References diam_avpgrp_add_raw(), and size.
Referenced by dm_grp_get_absticks(), dm_grp_get_addr(), dm_grp_get_binary(), dm_grp_get_bool(), dm_grp_get_counter(), dm_grp_get_date(), dm_grp_get_enum(), dm_grp_get_enumid(), dm_grp_get_int32(), dm_grp_get_int64(), dm_grp_get_path(), dm_grp_get_relticks(), dm_grp_get_string(), dm_grp_get_uint32(), dm_grp_get_uint64(), dm_grp_get_unknown(), and Lua_build_get_grp().
static int diam_avpgrp_add_uint64 (void * ctx, DIAM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint64_t data) inline static
Definition at line 342 of file diammsg.h.
References diam_avpgrp_add_raw(), and htonll.
static int diam_avpgrp_add_uint8 (void * ctx, DIAM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint8_t data) inline static
Definition at line 299 of file diammsg.h.
References diam_avpgrp_add_raw().
Referenced by dm_generic_register_request_bool_grp(), and dm_generic_send_request_bool_grp().
static int diam_avpgrp_get_avp (DIAM_AVPGRP * avpgrp, uint32_t * code, uint8_t * flags, uint32_t * vendor_id, void ** data, size_t * len) inline static
Definition at line 277 of file diammsg.h.
References diam_avpgrp_info::avpptr, diam_avpgrp_info::avps_length, get_avp(), and diam_avpgrp::info.
Referenced by dm_decode_absticks(), dm_decode_addr(), dm_decode_binary(), dm_decode_bool(), dm_decode_container(), dm_decode_counter(), dm_decode_date(), dm_decode_enum(), dm_decode_enumid(), dm_decode_int32(), dm_decode_int64(), dm_decode_node_list(), dm_decode_notifications(), dm_decode_path(), dm_decode_relticks(), dm_decode_sessionid(), dm_decode_string(), dm_decode_timeval(), dm_decode_type_path(), dm_decode_uint16(), dm_decode_uint32(), dm_decode_uint64(), dm_decode_unknown(), dump_avpgrp(), Lua_decode_get(), Lua_decode_list(), and Lua_decode_notifications().
static int diam_avpgrp_insert_avpgrp (void * ctx, DIAM_AVPGRP ** avpgrp, DIAM_AVPGRP * source) inline static
Definition at line 403 of file diammsg.h.
References diam_avpgrp_info::avps_length, diam_avpgrp_insert_raw(), and diam_avpgrp::info.
int diam_avpgrp_insert_raw (void * ctx, DIAM_AVPGRP ** avpgrp, const void * data, size_t len)
Definition at line 213 of file diammsg.c.
References diam_avpgrp_info::avps_length, DIAM_BLOCK_ALLOC, diam_avpgrp::info, and diam_avpgrp_info::size.
Referenced by diam_avpgrp_insert_avpgrp().
static void diam_avpgrp_reset_avp (DIAM_AVPGRP * avpgrp) inline static
Definition at line 272 of file diammsg.h.
References diam_avpgrp_info::avpptr, and diam_avpgrp::info.
Referenced by dm_decode_reset().
DIAM_AVPGRP* diam_decode_avpgrp (void * ctx, void * data, size_t len)
Definition at line 181 of file diammsg.c.
References diam_avpgrp_info::avpptr, diam_avpgrp_info::avps_length, diam_avpgrp::info, and diam_avpgrp_info::size.
Referenced by dm_decode_container(), dm_decode_node_list(), dm_decode_notifications(), dump_avpgrp(), dump_diam_packet(), Lua_decode_list(), process_active_notification(), and readEvent().
int diam_decode_complete (DIAM_REQUEST * req)
Definition at line 138 of file diammsg.c.
References diam_request_info::avpptr, diam_packet_length(), diam_request::info, diam_request::packet, and diam_request_info::size.
int diam_decode_request (void * ctx, DIAM_REQUEST ** req, void * data, size_t len)
start decoding a request received from the network minimum lenght of received data if 4 bytes
Parameters
ctx talloc memory context for request
req pointer to pointer to new request structure
data pointer to the data read from the network
len length of data
Returns
amount of data read form buffer
Definition at line 98 of file diammsg.c.
References diam_packet_length().
static uint32_t diam_end2end_id (DIAM_PACKET * pkt) inline static
Definition at line 242 of file diammsg.h.
References diam_packet::end2end_id.
int diam_get_address_avp (int * af, void * addr, const void * src)
Definition at line 308 of file diammsg.c.
References IANA_INET, and IANA_INET6.
Referenced by dm_decode_addr(), and dm_decode_unknown_as_string().
static int16_t diam_get_int16_avp (const void * src) inline static
Definition at line 431 of file diammsg.h.
static int32_t diam_get_int32_avp (const void * src) inline static
Definition at line 441 of file diammsg.h.
Referenced by dm_decode_enumid(), dm_decode_int32(), and dm_decode_unknown_as_string().
static int64_t diam_get_int64_avp (const void * src) inline static
Definition at line 451 of file diammsg.h.
References ntohll.
Referenced by dm_decode_absticks(), dm_decode_int64(), dm_decode_relticks(), and dm_decode_unknown_as_string().
static int8_t diam_get_int8_avp (const void * src) inline static
Definition at line 421 of file diammsg.h.
static int diam_get_string_avp (char * dest, size_t dlen, const void * src, size_t slen) inline static
Definition at line 408 of file diammsg.h.
static time_t diam_get_time_avp (const void * src) inline static
Definition at line 461 of file diammsg.h.
References diam_get_uint32_avp(), and TIME_SINCE_EPOCH.
Referenced by dm_decode_date(), and dm_decode_unknown_as_string().
static struct timeval diam_get_timeval_avp (const void * src) static
Definition at line 468 of file diammsg.h.
References diam_timeval::tv_sec, and diam_timeval::tv_usec.
Referenced by dm_decode_timeval().
static uint16_t diam_get_uint16_avp (const void * src) inline static
Definition at line 436 of file diammsg.h.
Referenced by dm_decode_uint16().
static uint32_t diam_get_uint32_avp (const void * src) inline static
Definition at line 446 of file diammsg.h.
Referenced by diam_get_time_avp(), dm_decode_counter(), dm_decode_node_list(), dm_decode_notifications(), dm_decode_sessionid(), dm_decode_type_path(), dm_decode_uint32(), dm_decode_unknown_as_string(), Lua_decode_list(), and readEvent().
static uint64_t diam_get_uint64_avp (const void * src) inline static
Definition at line 456 of file diammsg.h.
References ntohll.
Referenced by dm_decode_uint64(), and dm_decode_unknown_as_string().
static uint8_t diam_get_uint8_avp (const void * src) inline static
Definition at line 426 of file diammsg.h.
Referenced by dm_decode_bool(), and dm_decode_unknown_as_string().
static uint32_t diam_hop2hop_id (DIAM_PACKET * pkt) inline static
Definition at line 247 of file diammsg.h.
References diam_packet::hop2hop_id.
Referenced by readEvent().
static uint32_t diam_packet_code (DIAM_PACKET * pkt) inline static
Definition at line 232 of file diammsg.h.
References diam_packet::code, and uint24to32().
Referenced by dump_diam_packet(), and readEvent().
static uint8_t diam_packet_flags (DIAM_PACKET * pkt) inline static
Definition at line 222 of file diammsg.h.
References diam_packet::flags.
Referenced by readEvent().
static uint32_t diam_packet_length (DIAM_PACKET * pkt) inline static
Definition at line 227 of file diammsg.h.
References diam_packet::length, and uint24to32().
Referenced by diam_add_data(), diam_decode_complete(), diam_decode_request(), dump_diam_packet(), event_aux_diamRead(), and postprocessRequest().
static int diam_request_get_avp (DIAM_REQUEST * req, uint32_t * code, uint8_t * flags, uint32_t * vendor_id, void ** data, size_t * len) inline static
Definition at line 264 of file diammsg.h.
References diam_request_info::avpptr, get_avp(), diam_request::info, and diam_request_info::size.
Referenced by dump_diam_packet(), process_active_notification(), and readEvent().
static void diam_request_reset_avp (DIAM_REQUEST * req) inline static
Definition at line 259 of file diammsg.h.
References diam_request_info::avpptr, and diam_request::info.
Referenced by dump_diam_packet(), and readEvent().
int get_avp (uint32_t * code, uint8_t * flags, uint32_t * vendor_id, void ** data, size_t * len, DIAM_AVP ** src)
Definition at line 39 of file diammsg.c.
References AVP_FLAG_MANDATORY, AVP_FLAG_PRIVAT, AVP_FLAG_RESERVED, AVP_FLAG_VENDOR, diam_avp_length(), DIAM_INVALID_AVP_BITS, DIAM_INVALID_AVP_LENGTH, and PAD32.
Referenced by diam_avpgrp_get_avp(), and diam_request_get_avp().
DIAM_AVPGRP* new_diam_avpgrp (void * ctx)
Definition at line 167 of file diammsg.c.
References diam_avpgrp_info::avpptr, diam_avpgrp_info::avps_length, DIAM_BLOCK_ALLOC, diam_avpgrp::info, and diam_avpgrp_info::size.
Referenced by dm_generic_register_request(), dm_grp_new(), dm_grp_set(), and dm_grp_set_addr().
DIAM_REQUEST* new_diam_request (void * ctx, uint32_t code, uint8_t flags, uint32_t appid, uint32_t hopid, uint32_t endid)
Definition at line 67 of file diammsg.c.
References diam_packet::app_id, diam_packet::code, diam_packet::end2end_id, diam_packet::flags, flags, diam_packet::hop2hop_id, diam_request::info, diam_request::packet, diam_request_info::size, uint32to24(), and diam_packet::version.
Referenced by dm_generic_register_request().
static uint32_t uint24to32 (uint8_t i24[3]) inline static
Definition at line 210 of file diammsg.h.
Referenced by diam_avp_length(), diam_packet_code(), and diam_packet_length().
static void uint32to24 (uint8_t i24[3], uint32_t i32) inline static
Definition at line 215 of file diammsg.h.
Referenced by build_diam_request(), diam_avpgrp_add_raw(), and new_diam_request().
Variable Documentation
uint32_t app_id
Definition at line 313 of file diammsg.h.
DIAM_AVP * avpptr
Definition at line 309 of file diammsg.h.
uint32_t avps_length
Definition at line 311 of file diammsg.h.
uint8_t code
Definition at line 309 of file diammsg.h.
Referenced by dm_decode_absticks(), dm_decode_addr(), dm_decode_binary(), dm_decode_bool(), dm_decode_container(), dm_decode_counter(), dm_decode_date(), dm_decode_enum(), dm_decode_enumid(), dm_decode_int32(), dm_decode_int64(), dm_decode_node_list(), dm_decode_notifications(), dm_decode_path(), dm_decode_relticks(), dm_decode_sessionid(), dm_decode_string(), dm_decode_timeval(), dm_decode_type_path(), dm_decode_uint16(), dm_decode_uint32(), dm_decode_uint64(), dm_generic_register_request(), dump_avpgrp(), dump_diam_packet(), Lua_decode_list(), and Lua_register_eval().
uint32_t end2end_id
Definition at line 315 of file diammsg.h.
uint8_t flags
Definition at line 310 of file diammsg.h.
Referenced by dm_decode_absticks(), dm_decode_addr(), dm_decode_binary(), dm_decode_bool(), dm_decode_container(), dm_decode_counter(), dm_decode_date(), dm_decode_enum(), dm_decode_enumid(), dm_decode_int32(), dm_decode_int64(), dm_decode_node_list(), dm_decode_notifications(), dm_decode_path(), dm_decode_relticks(), dm_decode_sessionid(), dm_decode_string(), dm_decode_timeval(), dm_decode_type_path(), dm_decode_uint16(), dm_decode_uint32(), dm_decode_uint64(), dm_decode_unknown(), dm_register_connect_callback(), dump_avpgrp(), dump_diam_packet(), generic_Lua_callback(), Lua_decode_get(), Lua_decode_get_session_info(), Lua_decode_list(), Lua_decode_notifications(), LUA_SIG(), LUA_SIG_REGISTER(), new_diam_request(), process_active_notification(), and readEvent().
uint32_t hop2hop_id
Definition at line 314 of file diammsg.h.
DIAM_REQUEST_INFO info
Definition at line 309 of file diammsg.h.
uint8_t length
Definition at line 311 of file diammsg.h.
Referenced by event_aux_diamRead(), and event_aux_diamWrite().
DIAM_REQUEST* next
Definition at line 309 of file diammsg.h.
DIAM_PACKET packet
Definition at line 310 of file diammsg.h.
Referenced by dump_diam_packet().
uint32_t size
Definition at line 310 of file diammsg.h.
Referenced by connectEvent(), and diam_avpgrp_add_uint32_string().
uint32_t tv_sec
Definition at line 309 of file diammsg.h.
uint32_t tv_usec
Definition at line 310 of file diammsg.h.
uint32_t vendor_id
Definition at line 312 of file diammsg.h.
Referenced by dm_decode_absticks(), dm_decode_addr(), dm_decode_binary(), dm_decode_bool(), dm_decode_container(), dm_decode_counter(), dm_decode_date(), dm_decode_enum(), dm_decode_enumid(), dm_decode_int32(), dm_decode_int64(), dm_decode_node_list(), dm_decode_notifications(), dm_decode_path(), dm_decode_relticks(), dm_decode_sessionid(), dm_decode_string(), dm_decode_timeval(), dm_decode_type_path(), dm_decode_uint16(), dm_decode_uint32(), dm_decode_uint64(), dm_decode_unknown(), dump_avpgrp(), dump_diam_packet(), Lua_decode_get(), Lua_decode_list(), Lua_decode_notifications(), process_active_notification(), and readEvent().
uint8_t version
Definition at line 309 of file diammsg.h.