mand-1.0: libdmconfig/diammsg.c File Reference
diammsg.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdarg.h>
#include <stdint.h>
#include <string.h>
#include <inttypes.h>
#include <talloc.h>
#include "errors.h"
#include "codes.h"
#include "diammsg.h"
Functions
int get_avp (uint32_t *code, uint8_t *flags, uint32_t *vendor_id, void **data, size_t *len, DIAM_AVP **avp)
DIAM_REQUEST * new_diam_request (void *ctx, uint32_t code, uint8_t flags, uint32_t appid, uint32_t hopid, uint32_t endid)
int diam_decode_request (void *ctx, DIAM_REQUEST **req, void *data, size_t len)
start decoding a request received from the network minimum lenght of received data if 4 bytes
int diam_add_data (DIAM_REQUEST *req, void *data, size_t len)
int diam_decode_complete (DIAM_REQUEST *req)
int build_diam_request (void *ctx, DIAM_REQUEST **req, DIAM_AVPGRP *avpgrp)
DIAM_AVPGRP * new_diam_avpgrp (void *ctx)
DIAM_AVPGRP * diam_decode_avpgrp (void *ctx, void *data, size_t len)
int diam_avpgrp_add_avpgrp (void *ctx, DIAM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, DIAM_AVPGRP *source)
int diam_avpgrp_insert_raw (void *ctx, DIAM_AVPGRP **avpgrp, const void *data, size_t len)
int diam_avpgrp_add_raw (void *ctx, DIAM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, const void *data, size_t len)
int diam_avpgrp_add_address (void *ctx, DIAM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int af, const void *data)
int diam_avpgrp_add_uint32_string (void *ctx, DIAM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint32_t d1, const char *d2)
int diam_get_address_avp (int *af, void *addr, const void *src)
Function Documentation
int build_diam_request (void * ctx, DIAM_REQUEST ** req, DIAM_AVPGRP * avpgrp)
Definition at line 149 of file diammsg.c.
References diam_avpgrp_info::avps_length, diam_avpgrp::info, diam_request::info, diam_request_info::size, and uint32to24().
Referenced by dm_generic_register_request().
int diam_add_data (DIAM_REQUEST * req, void * data, size_t len)
Definition at line 121 of file diammsg.c.
References diam_request_info::avpptr, diam_packet_length(), diam_request::info, diam_request::packet, and diam_request_info::size.
int diam_avpgrp_add_address (void * ctx, DIAM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int af, const void * data)
Definition at line 267 of file diammsg.c.
References __attribute__(), diam_avpgrp_add_raw(), IANA_INET, and IANA_INET6.
Referenced by dm_generic_register_request_char_address(), dm_generic_send_request_char_address_get_char(), and dm_grp_set_addr().
int diam_avpgrp_add_avpgrp (void * ctx, DIAM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, DIAM_AVPGRP * source)
Definition at line 196 of file diammsg.c.
References AVP_FLAG_MANDATORY, diam_avpgrp_info::avps_length, diam_avp_length(), diam_avpgrp_add_raw(), diam_avpgrp::info, and PAD32.
Referenced by dm_generic_register_request(), dm_generic_register_request_bool_grp(), dm_generic_send_request_bool_grp(), dm_grp_set(), and dm_grp_set_addr().
int diam_avpgrp_add_raw (void * ctx, DIAM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, const void * data, size_t len)
Definition at line 229 of file diammsg.c.
References AVP_FLAG_MANDATORY, AVP_FLAG_PRIVAT, AVP_FLAG_VENDOR, diam_avpgrp_info::avps_length, diam_avp::code, DIAM_BLOCK_ALLOC, diam_avp::flags, diam_avpgrp::info, diam_avp::length, PAD32, diam_avpgrp_info::size, uint32to24(), and diam_avp::vendor_id.
Referenced by diam_avpgrp_add_address(), diam_avpgrp_add_avpgrp(), diam_avpgrp_add_float32(), diam_avpgrp_add_float64(), diam_avpgrp_add_int32(), diam_avpgrp_add_int64(), diam_avpgrp_add_int8(), diam_avpgrp_add_string(), diam_avpgrp_add_time(), diam_avpgrp_add_timeval(), diam_avpgrp_add_uint32(), diam_avpgrp_add_uint32_string(), diam_avpgrp_add_uint64(), diam_avpgrp_add_uint8(), and dm_grp_set().
int diam_avpgrp_add_uint32_string (void * ctx, DIAM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint32_t d1, const char * d2)
Definition at line 291 of file diammsg.c.
References diam_avpgrp_add_raw(), and size.
Referenced by dm_grp_get_absticks(), dm_grp_get_addr(), dm_grp_get_binary(), dm_grp_get_bool(), dm_grp_get_counter(), dm_grp_get_date(), dm_grp_get_enum(), dm_grp_get_enumid(), dm_grp_get_int32(), dm_grp_get_int64(), dm_grp_get_path(), dm_grp_get_relticks(), dm_grp_get_string(), dm_grp_get_uint32(), dm_grp_get_uint64(), dm_grp_get_unknown(), and Lua_build_get_grp().
int diam_avpgrp_insert_raw (void * ctx, DIAM_AVPGRP ** avpgrp, const void * data, size_t len)
Definition at line 213 of file diammsg.c.
References diam_avpgrp_info::avps_length, DIAM_BLOCK_ALLOC, diam_avpgrp::info, and diam_avpgrp_info::size.
Referenced by diam_avpgrp_insert_avpgrp().
DIAM_AVPGRP* diam_decode_avpgrp (void * ctx, void * data, size_t len)
Definition at line 181 of file diammsg.c.
References diam_avpgrp_info::avpptr, diam_avpgrp_info::avps_length, diam_avpgrp::info, and diam_avpgrp_info::size.
Referenced by dm_decode_container(), dm_decode_node_list(), dm_decode_notifications(), dump_avpgrp(), dump_diam_packet(), Lua_decode_list(), process_active_notification(), and readEvent().
int diam_decode_complete (DIAM_REQUEST * req)
Definition at line 138 of file diammsg.c.
References diam_request_info::avpptr, diam_packet_length(), diam_request::info, diam_request::packet, and diam_request_info::size.
int diam_decode_request (void * ctx, DIAM_REQUEST ** req, void * data, size_t len)
start decoding a request received from the network minimum lenght of received data if 4 bytes
Parameters
ctx talloc memory context for request
req pointer to pointer to new request structure
data pointer to the data read from the network
len length of data
Returns
amount of data read form buffer
Definition at line 98 of file diammsg.c.
References diam_packet_length().
int diam_get_address_avp (int * af, void * addr, const void * src)
Definition at line 308 of file diammsg.c.
References IANA_INET, and IANA_INET6.
Referenced by dm_decode_addr(), and dm_decode_unknown_as_string().
int get_avp (uint32_t * code, uint8_t * flags, uint32_t * vendor_id, void ** data, size_t * len, DIAM_AVP ** avp)
Definition at line 39 of file diammsg.c.
References AVP_FLAG_MANDATORY, AVP_FLAG_PRIVAT, AVP_FLAG_RESERVED, AVP_FLAG_VENDOR, diam_avp_length(), DIAM_INVALID_AVP_BITS, DIAM_INVALID_AVP_LENGTH, and PAD32.
Referenced by diam_avpgrp_get_avp(), and diam_request_get_avp().
DIAM_AVPGRP* new_diam_avpgrp (void * ctx)
Definition at line 167 of file diammsg.c.
References diam_avpgrp_info::avpptr, diam_avpgrp_info::avps_length, DIAM_BLOCK_ALLOC, diam_avpgrp::info, and diam_avpgrp_info::size.
Referenced by dm_generic_register_request(), dm_grp_new(), dm_grp_set(), and dm_grp_set_addr().
DIAM_REQUEST* new_diam_request (void * ctx, uint32_t code, uint8_t flags, uint32_t appid, uint32_t hopid, uint32_t endid)
Definition at line 67 of file diammsg.c.
References diam_packet::app_id, diam_packet::code, diam_packet::end2end_id, diam_packet::flags, flags, diam_packet::hop2hop_id, diam_request::info, diam_request::packet, diam_request_info::size, uint32to24(), and diam_packet::version.
Referenced by dm_generic_register_request().