mand-1.0: libdmconfig/dmconfig.h File Reference
dmconfig.h File Reference
#include <string.h>
#include <arpa/inet.h>
#include <sys/time.h>
#include <sys/un.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <unistd.h>
#include <ev.h>
#include <event.h>
#include <talloc.h>
#include "diammsg.h"
#include "codes.h"
Data Structures
struct requestInfo
struct commContext
struct dmContext
struct dmContext::_dmContext_callbacks
struct dmContext::_dmContext_callbacks::_callback_active_notification
struct conneventCtx
Macros
#define _GNU_SOURCE
#define SERVER_IP
#define ACCEPT_IP
#define SERVER_PORT
#define SERVER_LOCAL
#define MAX_INT
#define SESSIONCTX_DEFAULT_TIMEOUT
#define SESSIONCTX_MAX_TIMEOUT
#define TIMEOUT_CHUNKS
#define TIMEOUT_READ_REQUESTS
#define TIMEOUT_WRITE_REQUESTS
#define BUFFER_CHUNK_SIZE
#define DM_ADD_INSTANCE_AUTO
#define CMD_FLAG_READWRITE
#define CMD_FLAG_CONFIGURE
#define L_FOREACH(TYPE, CUR, HEAD)
#define LD_FREE(X)
#define LS_INSERT(HEAD, EL)
#define LD_INSERT(HEAD, EL)
Typedefs
typedef enum commStatus COMMSTATUS
typedef enum requestStatus REQUESTSTATUS
typedef enum dmconfig_event DMCONFIG_EVENT
typedef struct requestInfo REQUESTINFO
typedef struct dmContext DMCONTEXT
typedef void(* DMCONFIG_CALLBACK)(DMCONFIG_EVENT event, DMCONTEXT *dmCtx, void *user_data, uint32_t answer_rc, DIAM_AVPGRP *answer_grp)
typedef void(* DMCONFIG_CONNECT_CALLBACK)(DMCONFIG_EVENT event, DMCONTEXT *dmCtx, void *userdata)
typedef void(* DMCONFIG_ACTIVE_NOTIFY)(DMCONFIG_EVENT event, DMCONTEXT *dmCtx, void *userdata, DIAM_AVPGRP *answer)
typedef struct commContext COMMCONTEXT
typedef struct
_callback_active_notification ACTIVE_NOTIFY_INFO
typedef struct conneventCtx CONNEVENTCTX
Enumerations
enum commStatus {
COMPLETE, INCOMPLETE, NOTHING, CONNRESET,
ERROR
}
enum requestStatus { REQUEST_SHALL_WRITE, REQUEST_WRITING, REQUEST_SHALL_READ }
enum dmconfig_event {
DMCONFIG_ERROR_CONNECTING, DMCONFIG_ERROR_WRITING, DMCONFIG_ERROR_READING, DMCONFIG_ANSWER_READY,
DMCONFIG_CONNECTED
}
Functions
uint32_t event_aux_diamWrite (int fd, short event, COMMCONTEXT *writeCtx, COMMSTATUS *status)
uint32_t event_aux_diamRead (int fd, short event, COMMCONTEXT *readCtx, uint8_t *alreadyRead, COMMSTATUS *status)
void dm_free_requests (DMCONTEXT *dmCtx)
uint32_t dm_register_connect_callback (DMCONTEXT *dmCtx, int type, DMCONFIG_CONNECT_CALLBACK callback, void *userdata)
uint32_t dm_init_socket (DMCONTEXT *dmCtx, int type)
uint32_t dm_generic_register_request (DMCONTEXT *dmCtx, uint32_t code, DIAM_AVPGRP *grp, DMCONFIG_CALLBACK callback, void *callback_ud)
uint32_t dm_generic_register_request_bool_grp (DMCONTEXT *dmCtx, uint32_t code, uint8_t bool, DIAM_AVPGRP *grp, DMCONFIG_CALLBACK callback, void *callback_ud)
uint32_t dm_generic_register_request_uint32_timeouts (DMCONTEXT *dmCtx, uint32_t code, uint32_t val, struct timeval *timeval1, struct timeval *timeval2, DMCONFIG_CALLBACK callback, void *callback_ud)
uint32_t dm_generic_register_request_string (DMCONTEXT *dmCtx, uint32_t code, const char *str, DMCONFIG_CALLBACK callback, void *callback_ud)
uint32_t dm_generic_register_request_path (DMCONTEXT *dmCtx, uint32_t code, const char *path, DMCONFIG_CALLBACK callback, void *callback_ud)
uint32_t dm_generic_register_request_char_address (DMCONTEXT *dmCtx, uint32_t code, const char *str, struct in_addr addr, DMCONFIG_CALLBACK callback, void *callback_ud)
uint32_t dm_generic_send_request (DMCONTEXT *dmCtx, uint32_t code, DIAM_AVPGRP *grp, DIAM_AVPGRP **ret)
uint32_t dm_generic_send_request_bool_grp (DMCONTEXT *dmCtx, uint32_t code, uint8_t bool, DIAM_AVPGRP *grp)
uint32_t dm_generic_send_request_uint32_timeouts_get_grp (DMCONTEXT *dmCtx, uint32_t code, uint32_t val, struct timeval *timeval1, struct timeval *timeval2, DIAM_AVPGRP **ret)
uint32_t dm_generic_send_request_string (DMCONTEXT *dmCtx, uint32_t code, const char *str)
uint32_t dm_generic_send_request_path_get_grp (DMCONTEXT *dmCtx, uint32_t code, const char *path, DIAM_AVPGRP **answer)
uint32_t dm_generic_send_request_path_get_char (DMCONTEXT *dmCtx, uint32_t code, const char *path, char **data)
uint32_t dm_generic_send_request_char_address_get_char (DMCONTEXT *dmCtx, uint32_t code, const char *str, struct in_addr addr, char **data)
uint32_t dm_grp_set (DIAM_AVPGRP **grp, const char *name, int type, void *value, size_t size)
uint32_t dm_send_add_instance (DMCONTEXT *dmCtx, const char *path, uint16_t *instance)
uint32_t dm_send_list (DMCONTEXT *dmCtx, const char *name, uint16_t level, DIAM_AVPGRP **answer)
uint32_t dm_register_subscribe_notify (DMCONTEXT *dmCtx, DMCONFIG_ACTIVE_NOTIFY notify_callback, void *notify_callback_ud, DMCONFIG_CALLBACK callback, void *callback_ud)
uint32_t dm_register_add_instance (DMCONTEXT *dmCtx, const char *path, uint16_t instance, DMCONFIG_CALLBACK callback, void *callback_ud)
uint32_t dm_register_list (DMCONTEXT *dmCtx, const char *name, uint16_t level, DMCONFIG_CALLBACK callback, void *callback_ud)
uint32_t dm_decode_notifications (DIAM_AVPGRP *grp, uint32_t *type, DIAM_AVPGRP **notify)
uint32_t dm_decode_unknown_as_string (uint32_t type, void *data, size_t len, char **val)
uint32_t dm_decode_node_list (DIAM_AVPGRP *grp, char **name, uint32_t *type, uint32_t *size, uint32_t *datatype)
static DIAM_AVPGRP * dm_grp_new (void)
static void dm_grp_free (DIAM_AVPGRP *grp)
static uint32_t dm_grp_get_bool (DIAM_AVPGRP **grp, const char *name)
static uint32_t dm_grp_get_int32 (DIAM_AVPGRP **grp, const char *name)
static uint32_t dm_grp_get_uint32 (DIAM_AVPGRP **grp, const char *name)
static uint32_t dm_grp_get_int64 (DIAM_AVPGRP **grp, const char *name)
static uint32_t dm_grp_get_uint64 (DIAM_AVPGRP **grp, const char *name)
static uint32_t dm_grp_get_counter (DIAM_AVPGRP **grp, const char *name)
static uint32_t dm_grp_get_enumid (DIAM_AVPGRP **grp, const char *name)
static uint32_t dm_grp_get_enum (DIAM_AVPGRP **grp, const char *name)
static uint32_t dm_grp_get_string (DIAM_AVPGRP **grp, const char *name)
static uint32_t dm_grp_get_addr (DIAM_AVPGRP **grp, const char *name)
static uint32_t dm_grp_get_date (DIAM_AVPGRP **grp, const char *name)
static uint32_t dm_grp_get_absticks (DIAM_AVPGRP **grp, const char *name)
static uint32_t dm_grp_get_relticks (DIAM_AVPGRP **grp, const char *name)
static uint32_t dm_grp_get_path (DIAM_AVPGRP **grp, const char *name)
static uint32_t dm_grp_get_binary (DIAM_AVPGRP **grp, const char *name)
static uint32_t dm_grp_get_unknown (DIAM_AVPGRP **grp, const char *name)
static uint32_t dm_grp_set_bool (DIAM_AVPGRP **grp, const char *name, uint8_t value)
static uint32_t dm_grp_set_int32 (DIAM_AVPGRP **grp, const char *name, int32_t value)
static uint32_t dm_grp_set_uint32 (DIAM_AVPGRP **grp, const char *name, uint32_t value)
static uint32_t dm_grp_set_int64 (DIAM_AVPGRP **grp, const char *name, int64_t value)
static uint32_t dm_grp_set_uint64 (DIAM_AVPGRP **grp, const char *name, uint64_t value)
static uint32_t dm_grp_set_enumid (DIAM_AVPGRP **grp, const char *name, int32_t value)
static uint32_t dm_grp_set_enum (DIAM_AVPGRP **grp, const char *name, const char *value)
static uint32_t dm_grp_set_string (DIAM_AVPGRP **grp, const char *name, const char *value)
static uint32_t dm_grp_set_addr (DIAM_AVPGRP **grp, const char *name, struct in_addr addr)
static uint32_t dm_grp_set_date (DIAM_AVPGRP **grp, const char *name, time_t value)
static uint32_t dm_grp_set_absticks (DIAM_AVPGRP **grp, const char *name, int64_t value)
static uint32_t dm_grp_set_relticks (DIAM_AVPGRP **grp, const char *name, int64_t value)
static uint32_t dm_grp_set_path (DIAM_AVPGRP **grp, const char *name, const char *path)
static uint32_t dm_grp_set_binary (DIAM_AVPGRP **grp, const char *name, void *data, size_t len)
static uint32_t dm_grp_set_unknown (DIAM_AVPGRP **grp, const char *name, const char *value)
static uint32_t dm_grp_param_notify (DIAM_AVPGRP **grp, const char *name)
static void dm_context_init (DMCONTEXT *dmCtx, struct event_base *base)
static DMCONTEXT * dm_context_new (void *ctx, struct event_base *base)
static void dm_context_free (DMCONTEXT *dmCtx)
static void dm_context_set_socket (DMCONTEXT *dmCtx, int socket)
static int dm_context_get_socket (DMCONTEXT *dmCtx)
static void dm_context_set_sessionid (DMCONTEXT *dmCtx, uint32_t sessionid)
static uint32_t dm_context_get_sessionid (DMCONTEXT *dmCtx)
static void dm_context_set_event_base (DMCONTEXT *dmCtx, struct event_base *base)
static struct event_base * dm_context_get_event_base (DMCONTEXT *dmCtx)
static void dm_context_set_ev_loop (DMCONTEXT *dmCtx, struct ev_loop *loop)
static struct ev_loop * dm_context_get_ev_loop (DMCONTEXT *dmCtx)
static uint32_t dm_create_socket (DMCONTEXT *dmCtx, int type)
static void dm_shutdown_socket (DMCONTEXT *dmCtx)
static uint32_t dm_send_start_session (DMCONTEXT *dmCtx, uint32_t flags, struct timeval *timeout_session, struct timeval *timeout_request)
static uint32_t dm_send_switch_session (DMCONTEXT *dmCtx, uint32_t flags, struct timeval *timeout_session, struct timeval *timeout_request)
static uint32_t dm_send_get_session_info (DMCONTEXT *dmCtx, uint32_t *flags)
static uint32_t dm_send_get_cfg_session_info (DMCONTEXT *, uint32_t *, uint32_t *, struct timeval *)
static uint32_t dm_send_del_instance (DMCONTEXT *dmCtx, const char *path)
static uint32_t dm_send_find_instance (DMCONTEXT *dmCtx, const char *path, DIAM_AVPGRP *grp, uint16_t *inst)
static uint32_t dm_send_retrieve_enums (DMCONTEXT *dmCtx, const char *name, DIAM_AVPGRP **answer)
static uint32_t dm_send_subscribe_notify (DMCONTEXT *dmCtx)
static uint32_t dm_send_recursive_param_notify (DMCONTEXT *dmCtx, uint8_t isActiveNotify __attribute__((unused)), const char *path)
static uint32_t dm_send_packet_param_notify (DMCONTEXT *dmCtx, uint8_t isActiveNotify __attribute__((unused)), DIAM_AVPGRP *grp)
static uint32_t dm_send_get_passive_notifications (DMCONTEXT *dmCtx, DIAM_AVPGRP **answer)
static uint32_t dm_send_unsubscribe_notify (DMCONTEXT *dmCtx)
static uint32_t dm_send_end_session (DMCONTEXT *dmCtx)
static uint32_t dm_send_packet_set (DMCONTEXT *dmCtx, DIAM_AVPGRP *grp)
static uint32_t dm_send_packet_get (DMCONTEXT *dmCtx, DIAM_AVPGRP *grp, DIAM_AVPGRP **answer)
static uint32_t dm_send_commit (DMCONTEXT *dmCtx)
static uint32_t dm_send_cancel (DMCONTEXT *dmCtx)
static uint32_t dm_send_save (DMCONTEXT *dmCtx)
static uint32_t dm_send_cmd_dump (DMCONTEXT *dmCtx, const char *path, char **data)
static uint32_t dm_send_cmd_conf_save (DMCONTEXT *dmCtx, const char *server)
static uint32_t dm_send_cmd_conf_restore (DMCONTEXT *dmCtx, const char *server)
static uint32_t dm_register_start_session (DMCONTEXT *dmCtx, uint32_t flags, struct timeval *timeout_session, struct timeval *timeout_request, DMCONFIG_CALLBACK callback, void *callback_ud)
static uint32_t dm_register_switch_session (DMCONTEXT *dmCtx, uint32_t flags, struct timeval *timeout_session, struct timeval *timeout_request, DMCONFIG_CALLBACK callback, void *callback_ud)
static uint32_t dm_register_get_session_info (DMCONTEXT *dmCtx, DMCONFIG_CALLBACK callback, void *callback_ud)
static uint32_t dm_register_get_cfg_session_info (DMCONTEXT *, DMCONFIG_CALLBACK, void *)
static uint32_t dm_register_del_instance (DMCONTEXT *dmCtx, const char *path, DMCONFIG_CALLBACK callback, void *callback_ud)
static uint32_t dm_register_find_instance (DMCONTEXT *dmCtx, const char *path, DIAM_AVPGRP *grp, DMCONFIG_CALLBACK callback, void *callback_ud)
static uint32_t dm_register_retrieve_enums (DMCONTEXT *dmCtx, const char *name, DMCONFIG_CALLBACK callback, void *callback_ud)
static uint32_t dm_register_unsubscribe_notify (DMCONTEXT *dmCtx, DMCONFIG_CALLBACK callback, void *callback_ud)
static uint32_t dm_register_recursive_param_notify (DMCONTEXT *dmCtx, uint8_t isActiveNotify, const char *path, DMCONFIG_CALLBACK callback, void *callback_ud)
static uint32_t dm_register_packet_param_notify (DMCONTEXT *dmCtx, uint8_t isActiveNotify, DIAM_AVPGRP *grp, DMCONFIG_CALLBACK callback, void *callback_ud)
static uint32_t dm_register_get_passive_notifications (DMCONTEXT *dmCtx, DMCONFIG_CALLBACK callback, void *callback_ud)
static uint32_t dm_register_end_session (DMCONTEXT *dmCtx, DMCONFIG_CALLBACK callback, void *callback_ud)
static uint32_t dm_register_packet_set (DMCONTEXT *dmCtx, DIAM_AVPGRP *grp, DMCONFIG_CALLBACK callback, void *callback_ud)
static uint32_t dm_register_packet_get (DMCONTEXT *dmCtx, DIAM_AVPGRP *grp, DMCONFIG_CALLBACK callback, void *callback_ud)
static uint32_t dm_register_commit (DMCONTEXT *dmCtx, DMCONFIG_CALLBACK callback, void *callback_ud)
static uint32_t dm_register_cancel (DMCONTEXT *dmCtx, DMCONFIG_CALLBACK callback, void *callback_ud)
static uint32_t dm_register_save (DMCONTEXT *dmCtx, DMCONFIG_CALLBACK callback, void *callback_ud)
static uint32_t dm_register_cmd_dump (DMCONTEXT *dmCtx, const char *path, DMCONFIG_CALLBACK callback, void *callback_ud)
static uint32_t dm_register_cmd_conf_save (DMCONTEXT *dmCtx, const char *server, DMCONFIG_CALLBACK callback, void *callback_ud)
static uint32_t dm_register_cmd_conf_restore (DMCONTEXT *dmCtx, const char *server, DMCONFIG_CALLBACK callback, void *callback_ud)
static uint32_t dm_decode_start_session (DMCONTEXT *dmCtx, DIAM_AVPGRP *grp)
static uint32_t dm_decode_get_session_info (DIAM_AVPGRP *grp, uint32_t *flags)
static uint32_t dm_decode_get_cfg_session_info (DIAM_AVPGRP *, uint32_t *, uint32_t *, struct timeval *)
static uint32_t dm_decode_add_instance (DIAM_AVPGRP *grp, uint16_t *instance)
static uint32_t dm_decode_find_instance (DIAM_AVPGRP *grp, uint16_t *instance)
static uint32_t dm_decode_cmd_dump (DIAM_AVPGRP *grp, char **data)
static void dm_decode_reset (DIAM_AVPGRP *grp)
static uint32_t dm_decode_string (DIAM_AVPGRP *grp, char **val)
static uint32_t dm_decode_uint16 (DIAM_AVPGRP *grp, uint16_t *val)
static uint32_t dm_decode_uint32 (DIAM_AVPGRP *grp, uint32_t *val)
static uint32_t dm_decode_int32 (DIAM_AVPGRP *grp, int32_t *val)
static uint32_t dm_decode_uint64 (DIAM_AVPGRP *grp, uint64_t *val)
static uint32_t dm_decode_int64 (DIAM_AVPGRP *grp, int64_t *val)
static uint32_t dm_decode_sessionid (DIAM_AVPGRP *grp, uint32_t *val)
static uint32_t dm_decode_counter (DIAM_AVPGRP *grp, uint32_t *val)
static uint32_t dm_decode_enumid (DIAM_AVPGRP *grp, int32_t *val)
static uint32_t dm_decode_enum (DIAM_AVPGRP *grp, char **val)
static uint32_t dm_decode_bool (DIAM_AVPGRP *grp, uint8_t *val)
static uint32_t dm_decode_addr (DIAM_AVPGRP *grp, struct in_addr *addr)
static uint32_t dm_decode_date (DIAM_AVPGRP *grp, time_t *val)
static uint32_t dm_decode_timeval (DIAM_AVPGRP *grp, struct timeval *timeval)
static uint32_t dm_decode_absticks (DIAM_AVPGRP *grp, int64_t *val)
static uint32_t dm_decode_relticks (DIAM_AVPGRP *grp, int64_t *val)
static uint32_t dm_decode_path (DIAM_AVPGRP *grp, char **val)
static uint32_t dm_decode_binary (DIAM_AVPGRP *grp, void **val, size_t *len)
static uint32_t dm_decode_unknown (DIAM_AVPGRP *grp, uint32_t *type, void **val, size_t *size)
static uint32_t dm_decode_enumval (DIAM_AVPGRP *grp, char **val)
static uint32_t dm_decode_type_path (DIAM_AVPGRP *grp, uint32_t *v1, char **v2)
static uint32_t dm_decode_container (DIAM_AVPGRP *grp, DIAM_AVPGRP **container)
static uint32_t dm_decode_parameter_changed (DIAM_AVPGRP *notify, char **parameter, uint32_t *data_type)
static uint32_t dm_decode_instance_deleted (DIAM_AVPGRP *, char **)
static uint32_t dm_decode_instance_created (DIAM_AVPGRP *, char **)
Variables
int dmconfig_debug_level
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 21 of file dmconfig.h.
#define ACCEPT_IP
Definition at line 47 of file dmconfig.h.
#define BUFFER_CHUNK_SIZE
Definition at line 60 of file dmconfig.h.
Referenced by event_aux_diamRead().
#define CMD_FLAG_CONFIGURE
Definition at line 103 of file dmconfig.h.
Referenced by luaopen_libluadmconfig().
#define CMD_FLAG_READWRITE
Definition at line 102 of file dmconfig.h.
Referenced by LUA_SIG(), LUA_SIG_REGISTER(), and luaopen_libluadmconfig().
#define DM_ADD_INSTANCE_AUTO
Definition at line 62 of file dmconfig.h.
Referenced by LUA_SIG(), LUA_SIG_REGISTER(), and luaopen_libluadmconfig().
#define L_FOREACH (TYPE, CUR, HEAD)
Definition at line 172 of file dmconfig.h.
Referenced by writeEvent().
#define LD_FREE (X)
Definition at line 176 of file dmconfig.h.
#define LD_INSERT (HEAD, EL)
Definition at line 189 of file dmconfig.h.
#define LS_INSERT (HEAD, EL)
Definition at line 183 of file dmconfig.h.
#define MAX_INT
Definition at line 51 of file dmconfig.h.
Referenced by dm_generic_register_request().
#define SERVER_IP
Definition at line 46 of file dmconfig.h.
Referenced by dm_register_connect_callback().
#define SERVER_LOCAL
Definition at line 49 of file dmconfig.h.
Referenced by dm_register_connect_callback().
#define SERVER_PORT
Definition at line 48 of file dmconfig.h.
Referenced by dm_register_connect_callback().
#define SESSIONCTX_DEFAULT_TIMEOUT
Definition at line 53 of file dmconfig.h.
#define SESSIONCTX_MAX_TIMEOUT
Definition at line 54 of file dmconfig.h.
#define TIMEOUT_CHUNKS
Definition at line 56 of file dmconfig.h.
Referenced by readEvent(), and writeEvent().
#define TIMEOUT_READ_REQUESTS
Definition at line 57 of file dmconfig.h.
Referenced by readEvent(), and writeEvent().
#define TIMEOUT_WRITE_REQUESTS
Definition at line 58 of file dmconfig.h.
Referenced by dm_generic_register_request(), dm_register_connect_callback(), and writeEvent().
Typedef Documentation
typedef struct _callback_active_notification ACTIVE_NOTIFY_INFO
Definition at line 159 of file dmconfig.h.
typedef struct commContext COMMCONTEXT
typedef enum commStatus COMMSTATUS
typedef struct conneventCtx CONNEVENTCTX
typedef void(* DMCONFIG_ACTIVE_NOTIFY)(DMCONFIG_EVENT event, DMCONTEXT *dmCtx, void *userdata, DIAM_AVPGRP *answer)
Definition at line 114 of file dmconfig.h.
typedef void(* DMCONFIG_CALLBACK)(DMCONFIG_EVENT event, DMCONTEXT *dmCtx, void *user_data, uint32_t answer_rc, DIAM_AVPGRP *answer_grp)
Definition at line 108 of file dmconfig.h.
typedef void(* DMCONFIG_CONNECT_CALLBACK)(DMCONFIG_EVENT event, DMCONTEXT *dmCtx, void *userdata)
Definition at line 111 of file dmconfig.h.
typedef enum dmconfig_event DMCONFIG_EVENT
typedef struct dmContext DMCONTEXT
Definition at line 93 of file dmconfig.h.
typedef struct requestInfo REQUESTINFO
Definition at line 92 of file dmconfig.h.
typedef enum requestStatus REQUESTSTATUS
Enumeration Type Documentation
enum commStatus
Enumerator
COMPLETE
INCOMPLETE
NOTHING
CONNRESET
ERROR
Definition at line 66 of file dmconfig.h.
enum dmconfig_event
Enumerator
DMCONFIG_ERROR_CONNECTING
DMCONFIG_ERROR_WRITING
DMCONFIG_ERROR_READING
DMCONFIG_ANSWER_READY
DMCONFIG_CONNECTED
Definition at line 82 of file dmconfig.h.
enum requestStatus
Enumerator
REQUEST_SHALL_WRITE
REQUEST_WRITING
REQUEST_SHALL_READ
Definition at line 74 of file dmconfig.h.
Function Documentation
static void dm_context_free (DMCONTEXT * dmCtx) inline static
Definition at line 810 of file dmconfig.h.
static struct ev_loop * dm_context_get_ev_loop (DMCONTEXT * dmCtx) static
Definition at line 858 of file dmconfig.h.
References dmContext::evloop.
Referenced by dm_generic_send_request(), and dm_init_socket().
static struct event_base * dm_context_get_event_base (DMCONTEXT * dmCtx) static
Definition at line 846 of file dmconfig.h.
References dmContext::evloop.
Referenced by dm_generic_register_request(), dm_generic_send_request(), dm_init_socket(), dm_register_connect_callback(), and writeEvent().
static uint32_t dm_context_get_sessionid (DMCONTEXT * dmCtx) inline static
Definition at line 834 of file dmconfig.h.
References dmContext::sessionid.
Referenced by Lua_generic_get_sessionid().
static int dm_context_get_socket (DMCONTEXT * dmCtx) inline static
Definition at line 822 of file dmconfig.h.
References dmContext::socket.
Referenced by dm_register_connect_callback(), dmcontext_events_gc(), and dmcontext_sequential_gc().
static void dm_context_init (DMCONTEXT * dmCtx, struct event_base * base) inline static
Definition at line 791 of file dmconfig.h.
References dm_context_set_event_base().
Referenced by dm_context_new(), and Lua_init_eval().
static DMCONTEXT * dm_context_new (void * ctx, struct event_base * base) inline static
Definition at line 798 of file dmconfig.h.
References dm_context_init().
static void dm_context_set_ev_loop (DMCONTEXT * dmCtx, struct ev_loop * loop) inline static
Definition at line 852 of file dmconfig.h.
References dmContext::evloop.
static void dm_context_set_event_base (DMCONTEXT * dmCtx, struct event_base * base) inline static
Definition at line 840 of file dmconfig.h.
References dmContext::evloop.
Referenced by dm_context_init().
static void dm_context_set_sessionid (DMCONTEXT * dmCtx, uint32_t sessionid) inline static
Definition at line 828 of file dmconfig.h.
References dmContext::sessionid.
Referenced by dm_decode_start_session(), dm_send_end_session(), generic_Lua_callback(), and Lua_generic_set_sessionid().
static void dm_context_set_socket (DMCONTEXT * dmCtx, int socket) inline static
Definition at line 816 of file dmconfig.h.
References dmContext::socket.
Referenced by dm_create_socket(), and Lua_generic_shutdown().
static uint32_t dm_create_socket (DMCONTEXT * dmCtx, int type) inline static
Definition at line 864 of file dmconfig.h.
References dm_context_set_socket(), RC_ERR_CONNECTION, and RC_OK.
Referenced by dm_init_socket(), and LUA_SIG().
static uint32_t dm_decode_absticks (DIAM_AVPGRP * grp, int64_t * val) inline static
Definition at line 1569 of file dmconfig.h.
References AVP_ABSTICKS, code, diam_avpgrp_get_avp(), diam_get_int64_avp(), flags, RC_ERR_MISC, RC_OK, and vendor_id.
static uint32_t dm_decode_add_instance (DIAM_AVPGRP * grp, uint16_t * instance) inline static
Definition at line 1298 of file dmconfig.h.
References dm_decode_uint16().
Referenced by dm_send_add_instance().
static uint32_t dm_decode_addr (DIAM_AVPGRP * grp, struct in_addr * addr) inline static
Definition at line 1509 of file dmconfig.h.
References AVP_ADDRESS, code, diam_avpgrp_get_avp(), diam_get_address_avp(), flags, RC_ERR_MISC, RC_OK, and vendor_id.
static uint32_t dm_decode_binary (DIAM_AVPGRP * grp, void ** val, size_t * len) inline static
Definition at line 1619 of file dmconfig.h.
References AVP_BINARY, code, diam_avpgrp_get_avp(), flags, RC_ERR_MISC, RC_OK, and vendor_id.
static uint32_t dm_decode_bool (DIAM_AVPGRP * grp, uint8_t * val) inline static
Definition at line 1491 of file dmconfig.h.
References AVP_BOOL, code, diam_avpgrp_get_avp(), diam_get_uint8_avp(), flags, RC_ERR_MISC, RC_OK, and vendor_id.
static uint32_t dm_decode_cmd_dump (DIAM_AVPGRP * grp, char ** data) inline static
Definition at line 1310 of file dmconfig.h.
References dm_decode_string().
static uint32_t dm_decode_container (DIAM_AVPGRP * grp, DIAM_AVPGRP ** container) inline static
Definition at line 1673 of file dmconfig.h.
References AVP_CONTAINER, code, diam_avpgrp_get_avp(), diam_decode_avpgrp(), flags, RC_ERR_ALLOC, RC_ERR_MISC, RC_OK, and vendor_id.
static uint32_t dm_decode_counter (DIAM_AVPGRP * grp, uint32_t * val) inline static
Definition at line 1474 of file dmconfig.h.
References AVP_COUNTER, code, diam_avpgrp_get_avp(), diam_get_uint32_avp(), flags, RC_ERR_MISC, RC_OK, and vendor_id.
static uint32_t dm_decode_date (DIAM_AVPGRP * grp, time_t * val) inline static
Definition at line 1534 of file dmconfig.h.
References AVP_DATE, code, diam_avpgrp_get_avp(), diam_get_time_avp(), flags, RC_ERR_MISC, RC_OK, and vendor_id.
static uint32_t dm_decode_enum (DIAM_AVPGRP * grp, char ** val) inline static
Definition at line 1459 of file dmconfig.h.
References AVP_ENUM, code, diam_avpgrp_get_avp(), flags, RC_ERR_ALLOC, RC_ERR_MISC, RC_OK, and vendor_id.
static uint32_t dm_decode_enumid (DIAM_AVPGRP * grp, int32_t * val) inline static
Definition at line 1442 of file dmconfig.h.
References AVP_ENUMID, code, diam_avpgrp_get_avp(), diam_get_int32_avp(), flags, RC_ERR_MISC, RC_OK, and vendor_id.
static uint32_t dm_decode_enumval (DIAM_AVPGRP * grp, char ** val) inline static
Definition at line 1648 of file dmconfig.h.
References dm_decode_string().
Referenced by Lua_decode_retrieve_enums().
static uint32_t dm_decode_find_instance (DIAM_AVPGRP * grp, uint16_t * instance) inline static
Definition at line 1304 of file dmconfig.h.
References dm_decode_uint16().
Referenced by dm_send_find_instance().
static uint32_t dm_decode_get_cfg_session_info (DIAM_AVPGRP * grp, uint32_t * sessionid, uint32_t * flags, struct timeval * timeout) inline static
Definition at line 1289 of file dmconfig.h.
References dm_decode_sessionid(), dm_decode_timeval(), dm_decode_uint32(), RC_ERR_MISC, and RC_OK.
Referenced by dm_send_get_cfg_session_info(), and generic_Lua_callback().
static uint32_t dm_decode_get_session_info (DIAM_AVPGRP * grp, uint32_t * flags) inline static
Definition at line 1283 of file dmconfig.h.
References dm_decode_uint32().
Referenced by dm_send_get_session_info(), and Lua_decode_get_session_info().
static uint32_t dm_decode_instance_created (DIAM_AVPGRP * notify, char ** path) inline static
Definition at line 1703 of file dmconfig.h.
References dm_decode_path().
Referenced by Lua_decode_notifications().
static uint32_t dm_decode_instance_deleted (DIAM_AVPGRP * notify, char ** path) inline static
Definition at line 1697 of file dmconfig.h.
References dm_decode_path().
Referenced by Lua_decode_notifications().
static uint32_t dm_decode_int32 (DIAM_AVPGRP * grp, int32_t * val) inline static
Definition at line 1374 of file dmconfig.h.
References AVP_INT32, code, diam_avpgrp_get_avp(), diam_get_int32_avp(), flags, RC_ERR_MISC, RC_OK, and vendor_id.
static uint32_t dm_decode_int64 (DIAM_AVPGRP * grp, int64_t * val) inline static
Definition at line 1408 of file dmconfig.h.
References AVP_INT64, code, diam_avpgrp_get_avp(), diam_get_int64_avp(), flags, RC_ERR_MISC, RC_OK, and vendor_id.
uint32_t dm_decode_node_list (DIAM_AVPGRP * grp, char ** name, uint32_t * type, uint32_t * size, uint32_t * datatype)
Definition at line 1305 of file dmconfig.c.
References AVP_CONTAINER, AVP_NODE_DATATYPE, AVP_NODE_NAME, AVP_NODE_SIZE, AVP_NODE_TYPE, code, diam_avpgrp_get_avp(), diam_decode_avpgrp(), diam_get_uint32_avp(), dm_grp_free(), flags, NODE_OBJECT, NODE_PARAMETER, RC_ERR_ALLOC, RC_ERR_MISC, RC_OK, and vendor_id.
uint32_t dm_decode_notifications (DIAM_AVPGRP * grp, uint32_t * type, DIAM_AVPGRP ** notify)
Definition at line 1204 of file dmconfig.c.
References AVP_CONTAINER, AVP_NOTIFY_TYPE, code, diam_avpgrp_get_avp(), diam_decode_avpgrp(), diam_get_uint32_avp(), dm_grp_free(), flags, NOTIFY_NOTHING, RC_ERR_ALLOC, RC_ERR_MISC, RC_OK, and vendor_id.
Referenced by Lua_decode_notifications().
static uint32_t dm_decode_parameter_changed (DIAM_AVPGRP * notify, char ** parameter, uint32_t * data_type) inline static
Definition at line 1690 of file dmconfig.h.
References dm_decode_type_path().
Referenced by Lua_decode_notifications().
static uint32_t dm_decode_path (DIAM_AVPGRP * grp, char ** val) inline static
Definition at line 1603 of file dmconfig.h.
References AVP_PATH, code, diam_avpgrp_get_avp(), flags, RC_ERR_ALLOC, RC_ERR_MISC, RC_OK, and vendor_id.
Referenced by dm_decode_instance_created(), and dm_decode_instance_deleted().
static uint32_t dm_decode_relticks (DIAM_AVPGRP * grp, int64_t * val) inline static
Definition at line 1586 of file dmconfig.h.
References AVP_RELTICKS, code, diam_avpgrp_get_avp(), diam_get_int64_avp(), flags, RC_ERR_MISC, RC_OK, and vendor_id.
static void dm_decode_reset (DIAM_AVPGRP * grp) inline static
Definition at line 1318 of file dmconfig.h.
References diam_avpgrp_reset_avp().
static uint32_t dm_decode_sessionid (DIAM_AVPGRP * grp, uint32_t * val) inline static
Definition at line 1425 of file dmconfig.h.
References AVP_SESSIONID, code, diam_avpgrp_get_avp(), diam_get_uint32_avp(), flags, RC_ERR_MISC, RC_OK, and vendor_id.
Referenced by dm_decode_get_cfg_session_info(), and dm_decode_start_session().
static uint32_t dm_decode_start_session (DMCONTEXT * dmCtx, DIAM_AVPGRP * grp) inline static
Definition at line 1270 of file dmconfig.h.
References dm_context_set_sessionid(), dm_decode_sessionid(), and RC_OK.
Referenced by dm_send_start_session(), and generic_Lua_callback().
static uint32_t dm_decode_string (DIAM_AVPGRP * grp, char ** val) inline static
Definition at line 1324 of file dmconfig.h.
References AVP_STRING, code, diam_avpgrp_get_avp(), flags, RC_ERR_ALLOC, RC_ERR_MISC, RC_OK, and vendor_id.
Referenced by dm_decode_cmd_dump(), dm_decode_enumval(), dm_generic_send_request_char_address_get_char(), dm_generic_send_request_path_get_char(), and generic_Lua_callback().
static uint32_t dm_decode_timeval (DIAM_AVPGRP * grp, struct timeval * timeval) inline static
Definition at line 1551 of file dmconfig.h.
References AVP_TIMEVAL, code, diam_avpgrp_get_avp(), diam_get_timeval_avp(), flags, RC_ERR_MISC, RC_OK, and vendor_id.
Referenced by dm_decode_get_cfg_session_info().
static uint32_t dm_decode_type_path (DIAM_AVPGRP * grp, uint32_t * v1, char ** v2) inline static
Definition at line 1654 of file dmconfig.h.
References AVP_TYPE_PATH, code, diam_avpgrp_get_avp(), diam_get_uint32_avp(), flags, RC_ERR_ALLOC, RC_ERR_MISC, RC_OK, and vendor_id.
Referenced by dm_decode_parameter_changed().
static uint32_t dm_decode_uint16 (DIAM_AVPGRP * grp, uint16_t * val) inline static
Definition at line 1340 of file dmconfig.h.
References AVP_UINT16, code, diam_avpgrp_get_avp(), diam_get_uint16_avp(), flags, RC_ERR_MISC, RC_OK, and vendor_id.
Referenced by dm_decode_add_instance(), dm_decode_find_instance(), and generic_Lua_callback().
static uint32_t dm_decode_uint32 (DIAM_AVPGRP * grp, uint32_t * val) inline static
Definition at line 1357 of file dmconfig.h.
References AVP_UINT32, code, diam_avpgrp_get_avp(), diam_get_uint32_avp(), flags, RC_ERR_MISC, RC_OK, and vendor_id.
Referenced by dm_decode_get_cfg_session_info(), and dm_decode_get_session_info().
static uint32_t dm_decode_uint64 (DIAM_AVPGRP * grp, uint64_t * val) inline static
Definition at line 1391 of file dmconfig.h.
References AVP_UINT64, code, diam_avpgrp_get_avp(), diam_get_uint64_avp(), flags, RC_ERR_MISC, RC_OK, and vendor_id.
static uint32_t dm_decode_unknown (DIAM_AVPGRP * grp, uint32_t * type, void ** val, size_t * size) inline static
Definition at line 1631 of file dmconfig.h.
References diam_avpgrp_get_avp(), flags, RC_ERR_MISC, RC_OK, and vendor_id.
uint32_t dm_decode_unknown_as_string (uint32_t type, void * data, size_t len, char ** val)
Definition at line 1244 of file dmconfig.c.
References AVP_ABSTICKS, AVP_ADDRESS, AVP_BINARY, AVP_BOOL, AVP_COUNTER, AVP_DATE, AVP_ENUM, AVP_ENUMID, AVP_INT32, AVP_INT64, AVP_PATH, AVP_RELTICKS, AVP_STRING, AVP_UINT32, AVP_UINT64, diam_get_address_avp(), diam_get_int32_avp(), diam_get_int64_avp(), diam_get_time_avp(), diam_get_uint32_avp(), diam_get_uint64_avp(), diam_get_uint8_avp(), RC_ERR_ALLOC, RC_ERR_MISC, and RC_OK.
Referenced by Lua_decode_unknown().
void dm_free_requests (DMCONTEXT * dmCtx)
Definition at line 268 of file dmconfig.c.
References commContext::buffer, commContext::bytes, commContext::cAlloc, commContext::event, dmContext::readCtx, commContext::req, dmContext::requestlist_head, and dmContext::writeCtx.
Referenced by dmcontext_events_gc(), and dmcontext_sequential_gc().
uint32_t dm_generic_register_request (DMCONTEXT * dmCtx, uint32_t code, DIAM_AVPGRP * grp, DMCONFIG_CALLBACK callback, void * callback_ud)
Definition at line 358 of file dmconfig.c.
References APP_ID, AVP_CONTAINER, AVP_SESSIONID, build_diam_request(), CMD_FLAG_REQUEST, code, diam_avpgrp_add_avpgrp(), diam_avpgrp_add_uint32(), dm_context_get_event_base(), dmconfig_debug_level, dump_diam_packet(), endid, commContext::event, hopid, MAX_INT, new_diam_avpgrp(), new_diam_request(), requestInfo::next, RC_ERR_ALLOC, RC_OK, REQUEST_SHALL_WRITE, dmContext::requestlist_head, dmContext::sessionid, dmContext::socket, TIMEOUT_WRITE_REQUESTS, VP_TRAVELPING, dmContext::writeCtx, and writeEvent().
Referenced by dm_generic_register_request_bool_grp(), dm_generic_register_request_char_address(), dm_generic_register_request_path(), dm_generic_register_request_string(), dm_generic_register_request_uint32_timeouts(), dm_generic_send_request(), dm_register_add_instance(), dm_register_cancel(), dm_register_commit(), dm_register_end_session(), dm_register_find_instance(), dm_register_get_cfg_session_info(), dm_register_get_passive_notifications(), dm_register_get_session_info(), dm_register_list(), dm_register_packet_get(), dm_register_packet_set(), dm_register_save(), dm_register_subscribe_notify(), dm_register_unsubscribe_notify(), and Lua_generic_register().
uint32_t dm_generic_register_request_bool_grp (DMCONTEXT * dmCtx, uint32_t code, uint8_t bool, DIAM_AVPGRP * grp, DMCONFIG_CALLBACK callback, void * callback_ud)
Definition at line 438 of file dmconfig.c.
References AVP_BOOL, AVP_CONTAINER, diam_avpgrp_add_avpgrp(), diam_avpgrp_add_uint8(), dm_generic_register_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by dm_register_packet_param_notify(), and dm_register_recursive_param_notify().
uint32_t dm_generic_register_request_char_address (DMCONTEXT * dmCtx, uint32_t code, const char * str, struct in_addr addr, DMCONFIG_CALLBACK callback, void * callback_ud)
Definition at line 533 of file dmconfig.c.
References AVP_ADDRESS, AVP_STRING, diam_avpgrp_add_address(), diam_avpgrp_add_string(), dm_generic_register_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
uint32_t dm_generic_register_request_path (DMCONTEXT * dmCtx, uint32_t code, const char * path, DMCONFIG_CALLBACK callback, void * callback_ud)
Definition at line 512 of file dmconfig.c.
References AVP_PATH, diam_avpgrp_add_string(), dm_generic_register_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by dm_register_cmd_dump(), dm_register_del_instance(), and dm_register_retrieve_enums().
uint32_t dm_generic_register_request_string (DMCONTEXT * dmCtx, uint32_t code, const char * str, DMCONFIG_CALLBACK callback, void * callback_ud)
Definition at line 491 of file dmconfig.c.
References AVP_STRING, diam_avpgrp_add_string(), dm_generic_register_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by dm_register_cmd_conf_restore(), and dm_register_cmd_conf_save().
uint32_t dm_generic_register_request_uint32_timeouts (DMCONTEXT * dmCtx, uint32_t code, uint32_t val, struct timeval * timeval1, struct timeval * timeval2, DMCONFIG_CALLBACK callback, void * callback_ud)
Definition at line 462 of file dmconfig.c.
References AVP_TIMEOUT_REQUEST, AVP_TIMEOUT_SESSION, AVP_UINT32, diam_avpgrp_add_timeval(), diam_avpgrp_add_uint32(), dm_generic_register_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by dm_register_start_session(), and dm_register_switch_session().
uint32_t dm_generic_send_request (DMCONTEXT * dmCtx, uint32_t code, DIAM_AVPGRP * grp, DIAM_AVPGRP ** ret)
Definition at line 591 of file dmconfig.c.
References dm_context_get_ev_loop(), dm_context_get_event_base(), dm_generic_register_request(), generic_answerHandler(), RC_ERR_CONNECTION, and RC_ERR_MISC.
Referenced by dm_generic_send_request_bool_grp(), dm_generic_send_request_char_address_get_char(), dm_generic_send_request_path_get_grp(), dm_generic_send_request_string(), dm_generic_send_request_uint32_timeouts_get_grp(), dm_send_add_instance(), dm_send_cancel(), dm_send_commit(), dm_send_end_session(), dm_send_find_instance(), dm_send_get_cfg_session_info(), dm_send_get_passive_notifications(), dm_send_get_session_info(), dm_send_list(), dm_send_packet_get(), dm_send_packet_set(), dm_send_save(), dm_send_subscribe_notify(), dm_send_unsubscribe_notify(), Lua_generic_request(), and LUA_SIG().
uint32_t dm_generic_send_request_bool_grp (DMCONTEXT * dmCtx, uint32_t code, uint8_t bool, DIAM_AVPGRP * grp)
Definition at line 617 of file dmconfig.c.
References AVP_BOOL, AVP_CONTAINER, diam_avpgrp_add_avpgrp(), diam_avpgrp_add_uint8(), dm_generic_send_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by dm_send_packet_param_notify(), and dm_send_recursive_param_notify().
uint32_t dm_generic_send_request_char_address_get_char (DMCONTEXT * dmCtx, uint32_t code, const char * str, struct in_addr addr, char ** data)
Definition at line 727 of file dmconfig.c.
References AVP_ADDRESS, AVP_STRING, diam_avpgrp_add_address(), diam_avpgrp_add_string(), dm_decode_string(), dm_generic_send_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
uint32_t dm_generic_send_request_path_get_char (DMCONTEXT * dmCtx, uint32_t code, const char * path, char ** data)
Definition at line 713 of file dmconfig.c.
References dm_decode_string(), dm_generic_send_request_path_get_grp(), and dm_grp_free().
Referenced by dm_send_cmd_dump().
uint32_t dm_generic_send_request_path_get_grp (DMCONTEXT * dmCtx, uint32_t code, const char * path, DIAM_AVPGRP ** answer)
Definition at line 689 of file dmconfig.c.
References AVP_PATH, diam_avpgrp_add_string(), dm_generic_send_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
Referenced by dm_generic_send_request_path_get_char(), dm_send_del_instance(), and dm_send_retrieve_enums().
uint32_t dm_generic_send_request_string (DMCONTEXT * dmCtx, uint32_t code, const char * str)
Definition at line 671 of file dmconfig.c.
References AVP_STRING, diam_avpgrp_add_string(), dm_generic_send_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by dm_send_cmd_conf_restore(), and dm_send_cmd_conf_save().
uint32_t dm_generic_send_request_uint32_timeouts_get_grp (DMCONTEXT * dmCtx, uint32_t code, uint32_t val, struct timeval * timeval1, struct timeval * timeval2, DIAM_AVPGRP ** ret)
Definition at line 637 of file dmconfig.c.
References AVP_TIMEOUT_REQUEST, AVP_TIMEOUT_SESSION, AVP_UINT32, diam_avpgrp_add_timeval(), diam_avpgrp_add_uint32(), dm_generic_send_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
Referenced by dm_send_start_session(), and dm_send_switch_session().
static void dm_grp_free (DIAM_AVPGRP * grp) inline static
Definition at line 531 of file dmconfig.h.
Referenced by dm_decode_node_list(), dm_decode_notifications(), dm_generic_register_request_bool_grp(), dm_generic_register_request_char_address(), dm_generic_register_request_path(), dm_generic_register_request_string(), dm_generic_register_request_uint32_timeouts(), dm_generic_send_request_bool_grp(), dm_generic_send_request_char_address_get_char(), dm_generic_send_request_path_get_char(), dm_generic_send_request_path_get_grp(), dm_generic_send_request_string(), dm_generic_send_request_uint32_timeouts_get_grp(), dm_grp_set(), dm_grp_set_addr(), dm_register_add_instance(), dm_register_list(), dm_register_recursive_param_notify(), dm_send_add_instance(), dm_send_get_cfg_session_info(), dm_send_get_session_info(), dm_send_list(), dm_send_recursive_param_notify(), dm_send_start_session(), Lua_decode_list(), Lua_decode_notifications(), LUA_SIG(), and LUA_SIG_REGISTER().
static uint32_t dm_grp_get_absticks (DIAM_AVPGRP ** grp, const char * name) inline static
Definition at line 628 of file dmconfig.h.
References AVP_ABSTICKS, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_addr (DIAM_AVPGRP ** grp, const char * name) inline static
Definition at line 612 of file dmconfig.h.
References AVP_ADDRESS, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_binary (DIAM_AVPGRP ** grp, const char * name) inline static
Definition at line 652 of file dmconfig.h.
References AVP_BINARY, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_bool (DIAM_AVPGRP ** grp, const char * name) inline static
Definition at line 539 of file dmconfig.h.
References AVP_BOOL, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_counter (DIAM_AVPGRP ** grp, const char * name) inline static
Definition at line 579 of file dmconfig.h.
References AVP_COUNTER, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_date (DIAM_AVPGRP ** grp, const char * name) inline static
Definition at line 620 of file dmconfig.h.
References AVP_DATE, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_enum (DIAM_AVPGRP ** grp, const char * name) inline static
Definition at line 596 of file dmconfig.h.
References AVP_ENUM, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_enumid (DIAM_AVPGRP ** grp, const char * name) inline static
Definition at line 588 of file dmconfig.h.
References AVP_ENUMID, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_int32 (DIAM_AVPGRP ** grp, const char * name) inline static
Definition at line 547 of file dmconfig.h.
References AVP_INT32, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_int64 (DIAM_AVPGRP ** grp, const char * name) inline static
Definition at line 563 of file dmconfig.h.
References AVP_INT64, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_path (DIAM_AVPGRP ** grp, const char * name) inline static
Definition at line 644 of file dmconfig.h.
References AVP_PATH, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_relticks (DIAM_AVPGRP ** grp, const char * name) inline static
Definition at line 636 of file dmconfig.h.
References AVP_RELTICKS, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_string (DIAM_AVPGRP ** grp, const char * name) inline static
Definition at line 604 of file dmconfig.h.
References AVP_STRING, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_uint32 (DIAM_AVPGRP ** grp, const char * name) inline static
Definition at line 555 of file dmconfig.h.
References AVP_TYPE_PATH, AVP_UINT32, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_uint64 (DIAM_AVPGRP ** grp, const char * name) inline static
Definition at line 571 of file dmconfig.h.
References AVP_TYPE_PATH, AVP_UINT64, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_unknown (DIAM_AVPGRP ** grp, const char * name) inline static
Definition at line 660 of file dmconfig.h.
References AVP_TYPE_PATH, AVP_UNKNOWN, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static DIAM_AVPGRP * dm_grp_new (void) inline static
Definition at line 525 of file dmconfig.h.
References new_diam_avpgrp().
Referenced by dm_generic_register_request_bool_grp(), dm_generic_register_request_char_address(), dm_generic_register_request_path(), dm_generic_register_request_string(), dm_generic_register_request_uint32_timeouts(), dm_generic_send_request_bool_grp(), dm_generic_send_request_char_address_get_char(), dm_generic_send_request_path_get_grp(), dm_generic_send_request_string(), dm_generic_send_request_uint32_timeouts_get_grp(), dm_register_add_instance(), dm_register_list(), dm_register_recursive_param_notify(), dm_send_add_instance(), dm_send_list(), dm_send_recursive_param_notify(), Lua_build_get_grp(), Lua_build_param_notify_grp(), Lua_build_set_grp(), LUA_SIG(), and LUA_SIG_REGISTER().
static uint32_t dm_grp_param_notify (DIAM_AVPGRP ** grp, const char * name) inline static
Definition at line 782 of file dmconfig.h.
References AVP_PATH, diam_avpgrp_add_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
Referenced by Lua_build_param_notify_grp().
uint32_t dm_grp_set (DIAM_AVPGRP ** grp, const char * name, int type, void * value, size_t size)
Definition at line 1078 of file dmconfig.c.
References AVP_CONTAINER, AVP_PATH, diam_avpgrp_add_avpgrp(), diam_avpgrp_add_raw(), diam_avpgrp_add_string(), dm_grp_free(), new_diam_avpgrp(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
Referenced by dm_grp_set_absticks(), dm_grp_set_binary(), dm_grp_set_bool(), dm_grp_set_date(), dm_grp_set_enum(), dm_grp_set_enumid(), dm_grp_set_int32(), dm_grp_set_int64(), dm_grp_set_path(), dm_grp_set_relticks(), dm_grp_set_string(), dm_grp_set_uint32(), dm_grp_set_uint64(), dm_grp_set_unknown(), and Lua_encode_value().
static uint32_t dm_grp_set_absticks (DIAM_AVPGRP ** grp, const char * name, int64_t value) inline static
Definition at line 748 of file dmconfig.h.
References AVP_ABSTICKS, dm_grp_set(), and htonll.
static uint32_t dm_grp_set_addr (DIAM_AVPGRP ** grp, const char * name, struct in_addr addr) inline static
Definition at line 723 of file dmconfig.h.
References AVP_ADDRESS, AVP_CONTAINER, AVP_PATH, diam_avpgrp_add_address(), diam_avpgrp_add_avpgrp(), diam_avpgrp_add_string(), dm_grp_free(), new_diam_avpgrp(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
Referenced by Lua_encode_value().
static uint32_t dm_grp_set_binary (DIAM_AVPGRP ** grp, const char * name, void * data, size_t len) inline static
Definition at line 768 of file dmconfig.h.
References AVP_BINARY, and dm_grp_set().
Referenced by Lua_encode_value().
static uint32_t dm_grp_set_bool (DIAM_AVPGRP ** grp, const char * name, uint8_t value) inline static
Definition at line 670 of file dmconfig.h.
References AVP_BOOL, and dm_grp_set().
Referenced by Lua_encode_value().
static uint32_t dm_grp_set_date (DIAM_AVPGRP ** grp, const char * name, time_t value) inline static
Definition at line 741 of file dmconfig.h.
References AVP_DATE, and dm_grp_set().
Referenced by Lua_encode_value().
static uint32_t dm_grp_set_enum (DIAM_AVPGRP ** grp, const char * name, const char * value) inline static
Definition at line 711 of file dmconfig.h.
References AVP_ENUM, and dm_grp_set().
Referenced by Lua_encode_value().
static uint32_t dm_grp_set_enumid (DIAM_AVPGRP ** grp, const char * name, int32_t value) inline static
Definition at line 704 of file dmconfig.h.
References AVP_ENUMID, and dm_grp_set().
Referenced by Lua_encode_value().
static uint32_t dm_grp_set_int32 (DIAM_AVPGRP ** grp, const char * name, int32_t value) inline static
Definition at line 676 of file dmconfig.h.
References AVP_INT32, and dm_grp_set().
Referenced by Lua_encode_value().
static uint32_t dm_grp_set_int64 (DIAM_AVPGRP ** grp, const char * name, int64_t value) inline static
Definition at line 690 of file dmconfig.h.
References AVP_INT64, dm_grp_set(), and htonll.
static uint32_t dm_grp_set_path (DIAM_AVPGRP ** grp, const char * name, const char * path) inline static
Definition at line 762 of file dmconfig.h.
References AVP_PATH, and dm_grp_set().
Referenced by Lua_encode_value().
static uint32_t dm_grp_set_relticks (DIAM_AVPGRP ** grp, const char * name, int64_t value) inline static
Definition at line 755 of file dmconfig.h.
References AVP_RELTICKS, dm_grp_set(), and htonll.
static uint32_t dm_grp_set_string (DIAM_AVPGRP ** grp, const char * name, const char * value) inline static
Definition at line 717 of file dmconfig.h.
References AVP_STRING, and dm_grp_set().
Referenced by Lua_encode_value().
static uint32_t dm_grp_set_uint32 (DIAM_AVPGRP ** grp, const char * name, uint32_t value) inline static
Definition at line 683 of file dmconfig.h.
References AVP_UINT32, and dm_grp_set().
Referenced by Lua_encode_value().
static uint32_t dm_grp_set_uint64 (DIAM_AVPGRP ** grp, const char * name, uint64_t value) inline static
Definition at line 697 of file dmconfig.h.
References AVP_UINT64, dm_grp_set(), and htonll.
Referenced by Lua_encode_value().
static uint32_t dm_grp_set_unknown (DIAM_AVPGRP ** grp, const char * name, const char * value) inline static
Definition at line 774 of file dmconfig.h.
References AVP_UNKNOWN, and dm_grp_set().
Referenced by Lua_encode_value().
uint32_t dm_init_socket (DMCONTEXT * dmCtx, int type)
Definition at line 559 of file dmconfig.c.
References dm_context_get_ev_loop(), dm_context_get_event_base(), dm_create_socket(), dm_register_connect_callback(), generic_connectHandler(), and RC_ERR_MISC.
Referenced by LUA_SIG().
uint32_t dm_register_add_instance (DMCONTEXT * dmCtx, const char * path, uint16_t instance, DMCONFIG_CALLBACK callback, void * callback_ud)
Definition at line 1163 of file dmconfig.c.
References AVP_PATH, AVP_UINT16, CMD_DB_ADDINSTANCE, diam_avpgrp_add_string(), diam_avpgrp_add_uint16(), dm_generic_register_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_cancel (DMCONTEXT * dmCtx, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Definition at line 1229 of file dmconfig.h.
References CMD_DB_CANCEL, and dm_generic_register_request().
static uint32_t dm_register_cmd_conf_restore (DMCONTEXT * dmCtx, const char * server, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Definition at line 1260 of file dmconfig.h.
References CMD_DEV_CONF_RESTORE, and dm_generic_register_request_string().
static uint32_t dm_register_cmd_conf_save (DMCONTEXT * dmCtx, const char * server, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Definition at line 1252 of file dmconfig.h.
References CMD_DEV_CONF_SAVE, and dm_generic_register_request_string().
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_cmd_dump (DMCONTEXT * dmCtx, const char * path, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Definition at line 1244 of file dmconfig.h.
References CMD_DB_DUMP, and dm_generic_register_request_path().
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_commit (DMCONTEXT * dmCtx, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Definition at line 1221 of file dmconfig.h.
References CMD_DB_COMMIT, and dm_generic_register_request().
uint32_t dm_register_connect_callback (DMCONTEXT * dmCtx, int type, DMCONFIG_CONNECT_CALLBACK callback, void * userdata)
Definition at line 289 of file dmconfig.c.
References conneventCtx::callback, connectEvent(), dm_context_get_event_base(), dm_context_get_socket(), conneventCtx::dmCtx, conneventCtx::event, flags, RC_ERR_ALLOC, RC_ERR_CONNECTION, RC_OK, SERVER_IP, SERVER_LOCAL, SERVER_PORT, TIMEOUT_WRITE_REQUESTS, and conneventCtx::user_data.
Referenced by dm_init_socket(), and LUA_SIG_REGISTER().
static uint32_t dm_register_del_instance (DMCONTEXT * dmCtx, const char * path, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Definition at line 1124 of file dmconfig.h.
References CMD_DB_DELINSTANCE, and dm_generic_register_request_path().
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_end_session (DMCONTEXT * dmCtx, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Definition at line 1197 of file dmconfig.h.
References CMD_ENDSESSION, and dm_generic_register_request().
static uint32_t dm_register_find_instance (DMCONTEXT * dmCtx, const char * path, DIAM_AVPGRP * grp, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Definition at line 1132 of file dmconfig.h.
References AVP_PATH, CMD_DB_FINDINSTANCE, diam_avpgrp_add_string(), dm_generic_register_request(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_get_cfg_session_info (DMCONTEXT * dmCtx, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Definition at line 1116 of file dmconfig.h.
References CMD_CFGSESSIONINFO, and dm_generic_register_request().
static uint32_t dm_register_get_passive_notifications (DMCONTEXT * dmCtx, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Definition at line 1188 of file dmconfig.h.
References CMD_GET_PASSIVE_NOTIFICATIONS, and dm_generic_register_request().
static uint32_t dm_register_get_session_info (DMCONTEXT * dmCtx, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Definition at line 1108 of file dmconfig.h.
References CMD_SESSIONINFO, and dm_generic_register_request().
uint32_t dm_register_list (DMCONTEXT * dmCtx, const char * name, uint16_t level, DMCONFIG_CALLBACK callback, void * callback_ud)
Definition at line 1182 of file dmconfig.c.
References AVP_PATH, AVP_UINT16, CMD_DB_LIST, diam_avpgrp_add_string(), diam_avpgrp_add_uint16(), dm_generic_register_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_packet_get (DMCONTEXT * dmCtx, DIAM_AVPGRP * grp, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Definition at line 1213 of file dmconfig.h.
References CMD_DB_GET, and dm_generic_register_request().
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_packet_param_notify (DMCONTEXT * dmCtx, uint8_t isActiveNotify, DIAM_AVPGRP * grp, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Definition at line 1178 of file dmconfig.h.
References CMD_PARAM_NOTIFY, and dm_generic_register_request_bool_grp().
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_packet_set (DMCONTEXT * dmCtx, DIAM_AVPGRP * grp, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Definition at line 1205 of file dmconfig.h.
References CMD_DB_SET, and dm_generic_register_request().
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_recursive_param_notify (DMCONTEXT * dmCtx, uint8_t isActiveNotify, const char * path, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Definition at line 1156 of file dmconfig.h.
References AVP_PATH, CMD_RECURSIVE_PARAM_NOTIFY, diam_avpgrp_add_string(), dm_generic_register_request_bool_grp(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_retrieve_enums (DMCONTEXT * dmCtx, const char * name, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Definition at line 1140 of file dmconfig.h.
References CMD_DB_RETRIEVE_ENUMS, and dm_generic_register_request_path().
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_save (DMCONTEXT * dmCtx, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Definition at line 1237 of file dmconfig.h.
References CMD_DB_SAVE, and dm_generic_register_request().
static uint32_t dm_register_start_session (DMCONTEXT * dmCtx, uint32_t flags, struct timeval * timeout_session, struct timeval * timeout_request, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Definition at line 1080 of file dmconfig.h.
References CMD_STARTSESSION, and dm_generic_register_request_uint32_timeouts().
Referenced by LUA_SIG_REGISTER().
uint32_t dm_register_subscribe_notify (DMCONTEXT * dmCtx, DMCONFIG_ACTIVE_NOTIFY notify_callback, void * notify_callback_ud, DMCONFIG_CALLBACK callback, void * callback_ud)
Definition at line 1144 of file dmconfig.c.
References dmContext::_dmContext_callbacks::active_notification, dmContext::_dmContext_callbacks::_callback_active_notification::callback, dmContext::callbacks, CMD_SUBSCRIBE_NOTIFY, dm_generic_register_request(), RC_OK, and dmContext::_dmContext_callbacks::_callback_active_notification::user_data.
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_switch_session (DMCONTEXT * dmCtx, uint32_t flags, struct timeval * timeout_session, struct timeval * timeout_request, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Definition at line 1095 of file dmconfig.h.
References CMD_SWITCHSESSION, and dm_generic_register_request_uint32_timeouts().
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_unsubscribe_notify (DMCONTEXT * dmCtx, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Definition at line 1148 of file dmconfig.h.
References CMD_UNSUBSCRIBE_NOTIFY, and dm_generic_register_request().
Referenced by LUA_SIG_REGISTER().
uint32_t dm_send_add_instance (DMCONTEXT * dmCtx, const char * path, uint16_t * instance)
Definition at line 1099 of file dmconfig.c.
References AVP_PATH, AVP_UINT16, CMD_DB_ADDINSTANCE, diam_avpgrp_add_string(), diam_avpgrp_add_uint16(), dm_decode_add_instance(), dm_generic_send_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by LUA_SIG().
static uint32_t dm_send_cancel (DMCONTEXT * dmCtx) inline static
Definition at line 1049 of file dmconfig.h.
References CMD_DB_CANCEL, and dm_generic_send_request().
static uint32_t dm_send_cmd_conf_restore (DMCONTEXT * dmCtx, const char * server) inline static
Definition at line 1074 of file dmconfig.h.
References CMD_DEV_CONF_RESTORE, and dm_generic_send_request_string().
Referenced by LUA_SIG().
static uint32_t dm_send_cmd_conf_save (DMCONTEXT * dmCtx, const char * server) inline static
Definition at line 1068 of file dmconfig.h.
References CMD_DEV_CONF_SAVE, and dm_generic_send_request_string().
Referenced by LUA_SIG().
static uint32_t dm_send_cmd_dump (DMCONTEXT * dmCtx, const char * path, char ** data) inline static
Definition at line 1061 of file dmconfig.h.
References CMD_DB_DUMP, and dm_generic_send_request_path_get_char().
Referenced by LUA_SIG().
static uint32_t dm_send_commit (DMCONTEXT * dmCtx) inline static
Definition at line 1043 of file dmconfig.h.
References CMD_DB_COMMIT, and dm_generic_send_request().
static uint32_t dm_send_del_instance (DMCONTEXT * dmCtx, const char * path) inline static
Definition at line 947 of file dmconfig.h.
References CMD_DB_DELINSTANCE, and dm_generic_send_request_path_get_grp().
Referenced by LUA_SIG().
static uint32_t dm_send_end_session (DMCONTEXT * dmCtx) inline static
Definition at line 1019 of file dmconfig.h.
References CMD_ENDSESSION, dm_context_set_sessionid(), dm_generic_send_request(), and RC_OK.
Referenced by LUA_SIG().
static uint32_t dm_send_find_instance (DMCONTEXT * dmCtx, const char * path, DIAM_AVPGRP * grp, uint16_t * inst) inline static
Definition at line 954 of file dmconfig.h.
References AVP_PATH, CMD_DB_FINDINSTANCE, diam_avpgrp_add_string(), dm_decode_find_instance(), dm_generic_send_request(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by LUA_SIG().
static uint32_t dm_send_get_cfg_session_info (DMCONTEXT * dmCtx, uint32_t * sessionid, uint32_t * flags, struct timeval * timeout) inline static
Definition at line 933 of file dmconfig.h.
References CMD_CFGSESSIONINFO, dm_decode_get_cfg_session_info(), dm_generic_send_request(), and dm_grp_free().
Referenced by LUA_SIG().
static uint32_t dm_send_get_passive_notifications (DMCONTEXT * dmCtx, DIAM_AVPGRP ** answer) inline static
Definition at line 1006 of file dmconfig.h.
References CMD_GET_PASSIVE_NOTIFICATIONS, and dm_generic_send_request().
Referenced by LUA_SIG().
static uint32_t dm_send_get_session_info (DMCONTEXT * dmCtx, uint32_t * flags) inline static
Definition at line 919 of file dmconfig.h.
References CMD_SESSIONINFO, dm_decode_get_session_info(), dm_generic_send_request(), and dm_grp_free().
uint32_t dm_send_list (DMCONTEXT * dmCtx, const char * name, uint16_t level, DIAM_AVPGRP ** answer)
Definition at line 1122 of file dmconfig.c.
References AVP_PATH, AVP_UINT16, CMD_DB_LIST, diam_avpgrp_add_string(), diam_avpgrp_add_uint16(), dm_generic_send_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by LUA_SIG().
static uint32_t dm_send_packet_get (DMCONTEXT * dmCtx, DIAM_AVPGRP * grp, DIAM_AVPGRP ** answer) inline static
Definition at line 1037 of file dmconfig.h.
References CMD_DB_GET, and dm_generic_send_request().
Referenced by LUA_SIG().
static uint32_t dm_send_packet_param_notify (DMCONTEXT * dmCtx, uint8_t isActiveNotify __attribute__(unused), DIAM_AVPGRP * grp) inline static
Definition at line 998 of file dmconfig.h.
References CMD_PARAM_NOTIFY, and dm_generic_send_request_bool_grp().
Referenced by LUA_SIG().
static uint32_t dm_send_packet_set (DMCONTEXT * dmCtx, DIAM_AVPGRP * grp) inline static
Definition at line 1031 of file dmconfig.h.
References CMD_DB_SET, and dm_generic_send_request().
Referenced by LUA_SIG().
static uint32_t dm_send_recursive_param_notify (DMCONTEXT * dmCtx, uint8_t isActiveNotify __attribute__(unused), const char * path) inline static
Definition at line 978 of file dmconfig.h.
References AVP_PATH, CMD_RECURSIVE_PARAM_NOTIFY, diam_avpgrp_add_string(), dm_generic_send_request_bool_grp(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by LUA_SIG().
static uint32_t dm_send_retrieve_enums (DMCONTEXT * dmCtx, const char * name, DIAM_AVPGRP ** answer) inline static
Definition at line 965 of file dmconfig.h.
References CMD_DB_RETRIEVE_ENUMS, and dm_generic_send_request_path_get_grp().
Referenced by LUA_SIG().
static uint32_t dm_send_save (DMCONTEXT * dmCtx) inline static
Definition at line 1055 of file dmconfig.h.
References CMD_DB_SAVE, and dm_generic_send_request().
static uint32_t dm_send_start_session (DMCONTEXT * dmCtx, uint32_t flags, struct timeval * timeout_session, struct timeval * timeout_request) inline static
Definition at line 885 of file dmconfig.h.
References CMD_STARTSESSION, dm_decode_start_session(), dm_generic_send_request_uint32_timeouts_get_grp(), and dm_grp_free().
Referenced by LUA_SIG().
static uint32_t dm_send_subscribe_notify (DMCONTEXT * dmCtx) inline static
Definition at line 972 of file dmconfig.h.
References CMD_SUBSCRIBE_NOTIFY, and dm_generic_send_request().
static uint32_t dm_send_switch_session (DMCONTEXT * dmCtx, uint32_t flags, struct timeval * timeout_session, struct timeval * timeout_request) inline static
Definition at line 906 of file dmconfig.h.
References CMD_SWITCHSESSION, and dm_generic_send_request_uint32_timeouts_get_grp().
Referenced by LUA_SIG().
static uint32_t dm_send_unsubscribe_notify (DMCONTEXT * dmCtx) inline static
Definition at line 1013 of file dmconfig.h.
References CMD_UNSUBSCRIBE_NOTIFY, and dm_generic_send_request().
static void dm_shutdown_socket (DMCONTEXT * dmCtx) inline static
Definition at line 876 of file dmconfig.h.
References dmContext::socket.
Referenced by dmcontext_events_gc(), dmcontext_sequential_gc(), and Lua_generic_shutdown().
uint32_t event_aux_diamRead (int fd, short event, COMMCONTEXT * readCtx, uint8_t * alreadyRead, COMMSTATUS * status)
Definition at line 128 of file dmconfig.c.
References aux_RET, commContext::buffer, BUFFER_CHUNK_SIZE, commContext::bytes, commContext::cAlloc, COMPLETE, CONNRESET, debug, diam_packet_length(), ERROR, INCOMPLETE, length, NOTHING, diam_request::packet, postprocessRequest(), RC_ERR_ALLOC, RC_ERR_CONNECTION, RC_OK, and commContext::req.
Referenced by readEvent().
uint32_t event_aux_diamWrite (int fd, short event, COMMCONTEXT * writeCtx, COMMSTATUS * status)
Definition at line 220 of file dmconfig.c.
References aux_RET, aux_RET_SIG, commContext::buffer, commContext::bytes, COMPLETE, CONNRESET, ERROR, INCOMPLETE, diam_request::info, length, NOTHING, diam_request::packet, RC_ERR_CONNECTION, RC_OK, commContext::req, and diam_request_info::size.
Referenced by writeEvent().
Variable Documentation
int dmconfig_debug_level
Definition at line 61 of file dmconfig.c.
Referenced by dm_generic_register_request(), LUA_SIG(), and readEvent().