mand-1.0: libdmconfig/dmconfig.c File Reference
dmconfig.c File Reference
#include <errno.h>
#include <string.h>
#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdlib.h>
#include <time.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/time.h>
#include <sys/un.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <poll.h>
#include <fcntl.h>
#include <event.h>
#include <syslog.h>
#include <signal.h>
#include <talloc.h>
#include "diammsg.h"
#include "codes.h"
#include "dmconfig.h"
#include "utils/logx.h"
#include "utils/binary.h"
Macros
#define debug(format,...)
#define aux_RET(STATUS, RC)
#define aux_RET_SIG(STATUS, RC)
#define CALLBACK(WHERE,...)
#define NOTIFY_CALLBACK(EVENT, GRP)
Functions
static void postprocessRequest (COMMCONTEXT *ctx)
static void connectEvent (int fd, short event, void *arg)
static void writeEvent (int fd, short event, void *arg)
static void readEvent (int fd, short event, void *arg)
static int process_active_notification (DMCONTEXT *dmCtx)
static void generic_connectHandler (DMCONFIG_EVENT event, DMCONTEXT *dmCtx __attribute__((unused)), void *userdata)
static void generic_answerHandler (DMCONFIG_EVENT event __attribute__((unused)), DMCONTEXT *dmCtx __attribute__((unused)), void *user_data, uint32_t answer_rc, DIAM_AVPGRP *answer_grp)
uint32_t event_aux_diamRead (int fd, short event, COMMCONTEXT *readCtx, uint8_t *alreadyRead, COMMSTATUS *status)
uint32_t event_aux_diamWrite (int fd, short event, COMMCONTEXT *writeCtx, COMMSTATUS *status)
void dm_free_requests (DMCONTEXT *dmCtx)
uint32_t dm_register_connect_callback (DMCONTEXT *dmCtx, int type, DMCONFIG_CONNECT_CALLBACK callback, void *userdata)
uint32_t dm_generic_register_request (DMCONTEXT *dmCtx, uint32_t code, DIAM_AVPGRP *grp, DMCONFIG_CALLBACK callback, void *callback_ud)
uint32_t dm_generic_register_request_bool_grp (DMCONTEXT *dmCtx, uint32_t code, uint8_t bool, DIAM_AVPGRP *grp, DMCONFIG_CALLBACK callback, void *callback_ud)
uint32_t dm_generic_register_request_uint32_timeouts (DMCONTEXT *dmCtx, uint32_t code, uint32_t val, struct timeval *timeval1, struct timeval *timeval2, DMCONFIG_CALLBACK callback, void *callback_ud)
uint32_t dm_generic_register_request_string (DMCONTEXT *dmCtx, uint32_t code, const char *str, DMCONFIG_CALLBACK callback, void *callback_ud)
uint32_t dm_generic_register_request_path (DMCONTEXT *dmCtx, uint32_t code, const char *path, DMCONFIG_CALLBACK callback, void *callback_ud)
uint32_t dm_generic_register_request_char_address (DMCONTEXT *dmCtx, uint32_t code, const char *str, struct in_addr addr, DMCONFIG_CALLBACK callback, void *callback_ud)
uint32_t dm_init_socket (DMCONTEXT *dmCtx, int type)
uint32_t dm_generic_send_request (DMCONTEXT *dmCtx, uint32_t code, DIAM_AVPGRP *grp, DIAM_AVPGRP **ret)
uint32_t dm_generic_send_request_bool_grp (DMCONTEXT *dmCtx, uint32_t code, uint8_t bool, DIAM_AVPGRP *grp)
uint32_t dm_generic_send_request_uint32_timeouts_get_grp (DMCONTEXT *dmCtx, uint32_t code, uint32_t val, struct timeval *timeval1, struct timeval *timeval2, DIAM_AVPGRP **ret)
uint32_t dm_generic_send_request_string (DMCONTEXT *dmCtx, uint32_t code, const char *str)
uint32_t dm_generic_send_request_path_get_grp (DMCONTEXT *dmCtx, uint32_t code, const char *path, DIAM_AVPGRP **answer)
uint32_t dm_generic_send_request_path_get_char (DMCONTEXT *dmCtx, uint32_t code, const char *path, char **data)
uint32_t dm_generic_send_request_char_address_get_char (DMCONTEXT *dmCtx, uint32_t code, const char *str, struct in_addr addr, char **data)
uint32_t dm_grp_set (DIAM_AVPGRP **grp, const char *name, int type, void *value, size_t size)
uint32_t dm_send_add_instance (DMCONTEXT *dmCtx, const char *path, uint16_t *instance)
uint32_t dm_send_list (DMCONTEXT *dmCtx, const char *name, uint16_t level, DIAM_AVPGRP **answer)
uint32_t dm_register_subscribe_notify (DMCONTEXT *dmCtx, DMCONFIG_ACTIVE_NOTIFY notify_callback, void *notify_callback_ud, DMCONFIG_CALLBACK callback, void *callback_ud)
uint32_t dm_register_add_instance (DMCONTEXT *dmCtx, const char *path, uint16_t instance, DMCONFIG_CALLBACK callback, void *callback_ud)
uint32_t dm_register_list (DMCONTEXT *dmCtx, const char *name, uint16_t level, DMCONFIG_CALLBACK callback, void *callback_ud)
uint32_t dm_decode_notifications (DIAM_AVPGRP *grp, uint32_t *type, DIAM_AVPGRP **notify)
uint32_t dm_decode_unknown_as_string (uint32_t type, void *data, size_t len, char **val)
uint32_t dm_decode_node_list (DIAM_AVPGRP *grp, char **name, uint32_t *type, uint32_t *size, uint32_t *datatype)
Variables
int dmconfig_debug_level
static uint32_t hopid
static uint32_t endid
Macro Definition Documentation
#define aux_RET (STATUS, RC)
Definition at line 96 of file dmconfig.c.
Referenced by event_aux_diamRead(), and event_aux_diamWrite().
#define aux_RET_SIG (STATUS, RC)
Definition at line 100 of file dmconfig.c.
Referenced by event_aux_diamWrite().
#define CALLBACK (WHERE, ...)
Definition at line 106 of file dmconfig.c.
Referenced by connectEvent(), readEvent(), and writeEvent().
#define debug (format, ...)
Definition at line 63 of file dmconfig.c.
Referenced by event_aux_diamRead().
#define NOTIFY_CALLBACK (EVENT, GRP)
Definition at line 110 of file dmconfig.c.
Referenced by process_active_notification().
Function Documentation
static void connectEvent (int fd, short event, void * arg) static
Definition at line 775 of file dmconfig.c.
References CALLBACK, DMCONFIG_CONNECTED, DMCONFIG_ERROR_CONNECTING, conneventCtx::dmCtx, size, and conneventCtx::user_data.
Referenced by dm_register_connect_callback().
uint32_t dm_decode_node_list (DIAM_AVPGRP * grp, char ** name, uint32_t * type, uint32_t * size, uint32_t * datatype)
Definition at line 1305 of file dmconfig.c.
References AVP_CONTAINER, AVP_NODE_DATATYPE, AVP_NODE_NAME, AVP_NODE_SIZE, AVP_NODE_TYPE, code, diam_avpgrp_get_avp(), diam_decode_avpgrp(), diam_get_uint32_avp(), dm_grp_free(), flags, NODE_OBJECT, NODE_PARAMETER, RC_ERR_ALLOC, RC_ERR_MISC, RC_OK, and vendor_id.
uint32_t dm_decode_notifications (DIAM_AVPGRP * grp, uint32_t * type, DIAM_AVPGRP ** notify)
Definition at line 1204 of file dmconfig.c.
References AVP_CONTAINER, AVP_NOTIFY_TYPE, code, diam_avpgrp_get_avp(), diam_decode_avpgrp(), diam_get_uint32_avp(), dm_grp_free(), flags, NOTIFY_NOTHING, RC_ERR_ALLOC, RC_ERR_MISC, RC_OK, and vendor_id.
Referenced by Lua_decode_notifications().
uint32_t dm_decode_unknown_as_string (uint32_t type, void * data, size_t len, char ** val)
Definition at line 1244 of file dmconfig.c.
References AVP_ABSTICKS, AVP_ADDRESS, AVP_BINARY, AVP_BOOL, AVP_COUNTER, AVP_DATE, AVP_ENUM, AVP_ENUMID, AVP_INT32, AVP_INT64, AVP_PATH, AVP_RELTICKS, AVP_STRING, AVP_UINT32, AVP_UINT64, diam_get_address_avp(), diam_get_int32_avp(), diam_get_int64_avp(), diam_get_time_avp(), diam_get_uint32_avp(), diam_get_uint64_avp(), diam_get_uint8_avp(), RC_ERR_ALLOC, RC_ERR_MISC, and RC_OK.
Referenced by Lua_decode_unknown().
void dm_free_requests (DMCONTEXT * dmCtx)
Definition at line 268 of file dmconfig.c.
References commContext::buffer, commContext::bytes, commContext::cAlloc, commContext::event, dmContext::readCtx, commContext::req, dmContext::requestlist_head, and dmContext::writeCtx.
Referenced by dmcontext_events_gc(), and dmcontext_sequential_gc().
uint32_t dm_generic_register_request (DMCONTEXT * dmCtx, uint32_t code, DIAM_AVPGRP * grp, DMCONFIG_CALLBACK callback, void * callback_ud)
Definition at line 358 of file dmconfig.c.
References APP_ID, AVP_CONTAINER, AVP_SESSIONID, build_diam_request(), CMD_FLAG_REQUEST, code, diam_avpgrp_add_avpgrp(), diam_avpgrp_add_uint32(), dm_context_get_event_base(), dmconfig_debug_level, dump_diam_packet(), endid, commContext::event, hopid, MAX_INT, new_diam_avpgrp(), new_diam_request(), requestInfo::next, RC_ERR_ALLOC, RC_OK, REQUEST_SHALL_WRITE, dmContext::requestlist_head, dmContext::sessionid, dmContext::socket, TIMEOUT_WRITE_REQUESTS, VP_TRAVELPING, dmContext::writeCtx, and writeEvent().
Referenced by dm_generic_register_request_bool_grp(), dm_generic_register_request_char_address(), dm_generic_register_request_path(), dm_generic_register_request_string(), dm_generic_register_request_uint32_timeouts(), dm_generic_send_request(), dm_register_add_instance(), dm_register_cancel(), dm_register_commit(), dm_register_end_session(), dm_register_find_instance(), dm_register_get_cfg_session_info(), dm_register_get_passive_notifications(), dm_register_get_session_info(), dm_register_list(), dm_register_packet_get(), dm_register_packet_set(), dm_register_save(), dm_register_subscribe_notify(), dm_register_unsubscribe_notify(), and Lua_generic_register().
uint32_t dm_generic_register_request_bool_grp (DMCONTEXT * dmCtx, uint32_t code, uint8_t bool, DIAM_AVPGRP * grp, DMCONFIG_CALLBACK callback, void * callback_ud)
Definition at line 438 of file dmconfig.c.
References AVP_BOOL, AVP_CONTAINER, diam_avpgrp_add_avpgrp(), diam_avpgrp_add_uint8(), dm_generic_register_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by dm_register_packet_param_notify(), and dm_register_recursive_param_notify().
uint32_t dm_generic_register_request_char_address (DMCONTEXT * dmCtx, uint32_t code, const char * str, struct in_addr addr, DMCONFIG_CALLBACK callback, void * callback_ud)
Definition at line 533 of file dmconfig.c.
References AVP_ADDRESS, AVP_STRING, diam_avpgrp_add_address(), diam_avpgrp_add_string(), dm_generic_register_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
uint32_t dm_generic_register_request_path (DMCONTEXT * dmCtx, uint32_t code, const char * path, DMCONFIG_CALLBACK callback, void * callback_ud)
Definition at line 512 of file dmconfig.c.
References AVP_PATH, diam_avpgrp_add_string(), dm_generic_register_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by dm_register_cmd_dump(), dm_register_del_instance(), and dm_register_retrieve_enums().
uint32_t dm_generic_register_request_string (DMCONTEXT * dmCtx, uint32_t code, const char * str, DMCONFIG_CALLBACK callback, void * callback_ud)
Definition at line 491 of file dmconfig.c.
References AVP_STRING, diam_avpgrp_add_string(), dm_generic_register_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by dm_register_cmd_conf_restore(), and dm_register_cmd_conf_save().
uint32_t dm_generic_register_request_uint32_timeouts (DMCONTEXT * dmCtx, uint32_t code, uint32_t val, struct timeval * timeval1, struct timeval * timeval2, DMCONFIG_CALLBACK callback, void * callback_ud)
Definition at line 462 of file dmconfig.c.
References AVP_TIMEOUT_REQUEST, AVP_TIMEOUT_SESSION, AVP_UINT32, diam_avpgrp_add_timeval(), diam_avpgrp_add_uint32(), dm_generic_register_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by dm_register_start_session(), and dm_register_switch_session().
uint32_t dm_generic_send_request (DMCONTEXT * dmCtx, uint32_t code, DIAM_AVPGRP * grp, DIAM_AVPGRP ** ret)
Definition at line 591 of file dmconfig.c.
References dm_context_get_ev_loop(), dm_context_get_event_base(), dm_generic_register_request(), generic_answerHandler(), RC_ERR_CONNECTION, and RC_ERR_MISC.
Referenced by dm_generic_send_request_bool_grp(), dm_generic_send_request_char_address_get_char(), dm_generic_send_request_path_get_grp(), dm_generic_send_request_string(), dm_generic_send_request_uint32_timeouts_get_grp(), dm_send_add_instance(), dm_send_cancel(), dm_send_commit(), dm_send_end_session(), dm_send_find_instance(), dm_send_get_cfg_session_info(), dm_send_get_passive_notifications(), dm_send_get_session_info(), dm_send_list(), dm_send_packet_get(), dm_send_packet_set(), dm_send_save(), dm_send_subscribe_notify(), dm_send_unsubscribe_notify(), Lua_generic_request(), and LUA_SIG().
uint32_t dm_generic_send_request_bool_grp (DMCONTEXT * dmCtx, uint32_t code, uint8_t bool, DIAM_AVPGRP * grp)
Definition at line 617 of file dmconfig.c.
References AVP_BOOL, AVP_CONTAINER, diam_avpgrp_add_avpgrp(), diam_avpgrp_add_uint8(), dm_generic_send_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by dm_send_packet_param_notify(), and dm_send_recursive_param_notify().
uint32_t dm_generic_send_request_char_address_get_char (DMCONTEXT * dmCtx, uint32_t code, const char * str, struct in_addr addr, char ** data)
Definition at line 727 of file dmconfig.c.
References AVP_ADDRESS, AVP_STRING, diam_avpgrp_add_address(), diam_avpgrp_add_string(), dm_decode_string(), dm_generic_send_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
uint32_t dm_generic_send_request_path_get_char (DMCONTEXT * dmCtx, uint32_t code, const char * path, char ** data)
Definition at line 713 of file dmconfig.c.
References dm_decode_string(), dm_generic_send_request_path_get_grp(), and dm_grp_free().
Referenced by dm_send_cmd_dump().
uint32_t dm_generic_send_request_path_get_grp (DMCONTEXT * dmCtx, uint32_t code, const char * path, DIAM_AVPGRP ** answer)
Definition at line 689 of file dmconfig.c.
References AVP_PATH, diam_avpgrp_add_string(), dm_generic_send_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
Referenced by dm_generic_send_request_path_get_char(), dm_send_del_instance(), and dm_send_retrieve_enums().
uint32_t dm_generic_send_request_string (DMCONTEXT * dmCtx, uint32_t code, const char * str)
Definition at line 671 of file dmconfig.c.
References AVP_STRING, diam_avpgrp_add_string(), dm_generic_send_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by dm_send_cmd_conf_restore(), and dm_send_cmd_conf_save().
uint32_t dm_generic_send_request_uint32_timeouts_get_grp (DMCONTEXT * dmCtx, uint32_t code, uint32_t val, struct timeval * timeval1, struct timeval * timeval2, DIAM_AVPGRP ** ret)
Definition at line 637 of file dmconfig.c.
References AVP_TIMEOUT_REQUEST, AVP_TIMEOUT_SESSION, AVP_UINT32, diam_avpgrp_add_timeval(), diam_avpgrp_add_uint32(), dm_generic_send_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
Referenced by dm_send_start_session(), and dm_send_switch_session().
uint32_t dm_grp_set (DIAM_AVPGRP ** grp, const char * name, int type, void * value, size_t size)
Definition at line 1078 of file dmconfig.c.
References AVP_CONTAINER, AVP_PATH, diam_avpgrp_add_avpgrp(), diam_avpgrp_add_raw(), diam_avpgrp_add_string(), dm_grp_free(), new_diam_avpgrp(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
Referenced by dm_grp_set_absticks(), dm_grp_set_binary(), dm_grp_set_bool(), dm_grp_set_date(), dm_grp_set_enum(), dm_grp_set_enumid(), dm_grp_set_int32(), dm_grp_set_int64(), dm_grp_set_path(), dm_grp_set_relticks(), dm_grp_set_string(), dm_grp_set_uint32(), dm_grp_set_uint64(), dm_grp_set_unknown(), and Lua_encode_value().
uint32_t dm_init_socket (DMCONTEXT * dmCtx, int type)
Definition at line 559 of file dmconfig.c.
References dm_context_get_ev_loop(), dm_context_get_event_base(), dm_create_socket(), dm_register_connect_callback(), generic_connectHandler(), and RC_ERR_MISC.
Referenced by LUA_SIG().
uint32_t dm_register_add_instance (DMCONTEXT * dmCtx, const char * path, uint16_t instance, DMCONFIG_CALLBACK callback, void * callback_ud)
Definition at line 1163 of file dmconfig.c.
References AVP_PATH, AVP_UINT16, CMD_DB_ADDINSTANCE, diam_avpgrp_add_string(), diam_avpgrp_add_uint16(), dm_generic_register_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by LUA_SIG_REGISTER().
uint32_t dm_register_connect_callback (DMCONTEXT * dmCtx, int type, DMCONFIG_CONNECT_CALLBACK callback, void * userdata)
Definition at line 289 of file dmconfig.c.
References conneventCtx::callback, connectEvent(), dm_context_get_event_base(), dm_context_get_socket(), conneventCtx::dmCtx, conneventCtx::event, flags, RC_ERR_ALLOC, RC_ERR_CONNECTION, RC_OK, SERVER_IP, SERVER_LOCAL, SERVER_PORT, TIMEOUT_WRITE_REQUESTS, and conneventCtx::user_data.
Referenced by dm_init_socket(), and LUA_SIG_REGISTER().
uint32_t dm_register_list (DMCONTEXT * dmCtx, const char * name, uint16_t level, DMCONFIG_CALLBACK callback, void * callback_ud)
Definition at line 1182 of file dmconfig.c.
References AVP_PATH, AVP_UINT16, CMD_DB_LIST, diam_avpgrp_add_string(), diam_avpgrp_add_uint16(), dm_generic_register_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by LUA_SIG_REGISTER().
uint32_t dm_register_subscribe_notify (DMCONTEXT * dmCtx, DMCONFIG_ACTIVE_NOTIFY notify_callback, void * notify_callback_ud, DMCONFIG_CALLBACK callback, void * callback_ud)
Definition at line 1144 of file dmconfig.c.
References dmContext::_dmContext_callbacks::active_notification, dmContext::_dmContext_callbacks::_callback_active_notification::callback, dmContext::callbacks, CMD_SUBSCRIBE_NOTIFY, dm_generic_register_request(), RC_OK, and dmContext::_dmContext_callbacks::_callback_active_notification::user_data.
Referenced by LUA_SIG_REGISTER().
uint32_t dm_send_add_instance (DMCONTEXT * dmCtx, const char * path, uint16_t * instance)
Definition at line 1099 of file dmconfig.c.
References AVP_PATH, AVP_UINT16, CMD_DB_ADDINSTANCE, diam_avpgrp_add_string(), diam_avpgrp_add_uint16(), dm_decode_add_instance(), dm_generic_send_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by LUA_SIG().
uint32_t dm_send_list (DMCONTEXT * dmCtx, const char * name, uint16_t level, DIAM_AVPGRP ** answer)
Definition at line 1122 of file dmconfig.c.
References AVP_PATH, AVP_UINT16, CMD_DB_LIST, diam_avpgrp_add_string(), diam_avpgrp_add_uint16(), dm_generic_send_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by LUA_SIG().
uint32_t event_aux_diamRead (int fd, short event, COMMCONTEXT * readCtx, uint8_t * alreadyRead, COMMSTATUS * status)
Definition at line 128 of file dmconfig.c.
References aux_RET, commContext::buffer, BUFFER_CHUNK_SIZE, commContext::bytes, commContext::cAlloc, COMPLETE, CONNRESET, debug, diam_packet_length(), ERROR, INCOMPLETE, length, NOTHING, diam_request::packet, postprocessRequest(), RC_ERR_ALLOC, RC_ERR_CONNECTION, RC_OK, and commContext::req.
Referenced by readEvent().
uint32_t event_aux_diamWrite (int fd, short event, COMMCONTEXT * writeCtx, COMMSTATUS * status)
Definition at line 220 of file dmconfig.c.
References aux_RET, aux_RET_SIG, commContext::buffer, commContext::bytes, COMPLETE, CONNRESET, ERROR, INCOMPLETE, diam_request::info, length, NOTHING, diam_request::packet, RC_ERR_CONNECTION, RC_OK, commContext::req, and diam_request_info::size.
Referenced by writeEvent().
static void generic_answerHandler (DMCONFIG_EVENT event __attribute__(unused), DMCONTEXT *dmCtx __attribute__(unused), void * user_data, uint32_t answer_rc, DIAM_AVPGRP * answer_grp) static
Definition at line 752 of file dmconfig.c.
Referenced by dm_generic_send_request().
static void generic_connectHandler (DMCONFIG_EVENT event, DMCONTEXT *dmCtx __attribute__(unused), void * userdata) static
Definition at line 581 of file dmconfig.c.
References DMCONFIG_ERROR_CONNECTING, RC_ERR_CONNECTION, and RC_OK.
Referenced by dm_init_socket().
static void postprocessRequest (COMMCONTEXT * ctx) inline static
Definition at line 120 of file dmconfig.c.
References diam_request_info::avpptr, commContext::buffer, diam_packet_length(), diam_request::info, diam_request::packet, commContext::req, and diam_request_info::size.
Referenced by event_aux_diamRead().
static int process_active_notification (DMCONTEXT * dmCtx) inline static
Definition at line 1047 of file dmconfig.c.
References dmContext::_dmContext_callbacks::active_notification, AVP_CONTAINER, dmContext::_dmContext_callbacks::_callback_active_notification::callback, dmContext::callbacks, diam_decode_avpgrp(), diam_request_get_avp(), DMCONFIG_ANSWER_READY, DMCONFIG_ERROR_READING, flags, NOTIFY_CALLBACK, dmContext::readCtx, commContext::req, and vendor_id.
static void readEvent (int fd, short event, void * arg) static
Definition at line 886 of file dmconfig.c.
References dmContext::_dmContext_callbacks::active_notification, AVP_CONTAINER, AVP_RC, commContext::bytes, CALLBACK, dmContext::_dmContext_callbacks::_callback_active_notification::callback, dmContext::callbacks, commContext::cAlloc, CMD_ENDSESSION, CMD_FLAG_REQUEST, CMD_SUBSCRIBE_NOTIFY, CMD_UNSUBSCRIBE_NOTIFY, requestInfo::code, COMPLETE, diam_decode_avpgrp(), diam_get_uint32_avp(), diam_hop2hop_id(), diam_packet_code(), diam_packet_flags(), diam_request_get_avp(), diam_request_reset_avp(), DMCONFIG_ANSWER_READY, dmconfig_debug_level, DMCONFIG_ERROR_READING, requestInfo::dmCtx, dump_diam_packet(), commContext::event, event_aux_diamRead(), flags, hopid, requestInfo::hopid, INCOMPLETE, requestInfo::next, NOTHING, diam_request::packet, RC_ERR_ALLOC, RC_ERR_MISC, RC_OK, dmContext::readCtx, commContext::req, REQUEST_SHALL_READ, dmContext::requestlist_head, requestInfo::status, TIMEOUT_CHUNKS, TIMEOUT_READ_REQUESTS, requestInfo::user_data, and vendor_id.
Referenced by writeEvent().
static void writeEvent (int fd, short event, void * arg) static
Definition at line 794 of file dmconfig.c.
References commContext::buffer, CALLBACK, COMPLETE, commContext::cur_request, dm_context_get_event_base(), DMCONFIG_ERROR_WRITING, requestInfo::dmCtx, commContext::event, event_aux_diamWrite(), INCOMPLETE, L_FOREACH, requestInfo::next, NOTHING, RC_ERR_ALLOC, dmContext::readCtx, readEvent(), commContext::req, requestInfo::request, REQUEST_SHALL_READ, REQUEST_SHALL_WRITE, REQUEST_WRITING, dmContext::requestlist_head, dmContext::socket, requestInfo::status, TIMEOUT_CHUNKS, TIMEOUT_READ_REQUESTS, TIMEOUT_WRITE_REQUESTS, requestInfo::user_data, and dmContext::writeCtx.
Referenced by dm_generic_register_request().
Variable Documentation
int dmconfig_debug_level
Definition at line 61 of file dmconfig.c.
Referenced by dm_generic_register_request(), LUA_SIG(), and readEvent().
uint32_t endid static
Definition at line 94 of file dmconfig.c.
Referenced by dm_generic_register_request().
uint32_t hopid static
Definition at line 93 of file dmconfig.c.
Referenced by dm_generic_register_request(), and readEvent().