mand-1.0: libdmconfig/luawrapper.c File Reference
luawrapper.c File Reference
#include <errno.h>
#include <string.h>
#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdlib.h>
#include <time.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/time.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <poll.h>
#include <fcntl.h>
#include <event.h>
#include <lua.h>
#include <lauxlib.h>
#include "diammsg.h"
#include "codes.h"
#include "dmconfig.h"
#include "mand/dm_lua.h"
#include "utils/logx.h"
#include "utils/binary.h"
Data Structures
struct _Lua_callback
Macros
#define LUA_SIG_REGISTER(name)
#define LSTD_FUNC_BOTH(FNAME, CODE)
#define LUA_HEADER_BOTH(name)
#define L_SESSIONID
#define EVENT_BASE_MT
#define DMCONFIG_SESSION_SEQUENTIAL_MT
#define DMCONFIG_SESSION_EVENTS_MT
#define DMCONFIG_CALLBACK_MT
#define PTABLE_ERR()
#define TABLE_ERR2()
#define TABLE_ERR()
#define LSTD_FUNC(FNAME, CODE)
#define LSTD_FUNC_REGISTER(FNAME, CODE)
#define NAMETOFUNC_REGISTER(NAME)
Typedefs
typedef struct _Lua_callback LUA_CALLBACK
Functions
static uint32_t Lua_decode_get_session_info (lua_State *L, DIAM_AVPGRP *answer)
static uint32_t Lua_decode_get_cfg_session_info (lua_State *L, uint32_t sessionid, uint32_t flags, struct timeval timeout)
static uint32_t Lua_decode_unknown (lua_State *L, uint32_t type, void *data, size_t len)
static uint32_t Lua_decode_get (lua_State *L, DIAM_AVPGRP *answer)
static uint32_t Lua_decode_list (lua_State *L, DIAM_AVPGRP *grp, int *nodes)
static uint32_t Lua_decode_retrieve_enums (lua_State *L, DIAM_AVPGRP *answer)
static uint32_t Lua_decode_notifications (lua_State *L, DIAM_AVPGRP *answer)
static void generic_Lua_callback (DMCONFIG_EVENT event, DMCONTEXT *dmCtx, void *user_data, uint32_t answer_rc, DIAM_AVPGRP *answer_grp)
static void generic_Lua_connect_callback (DMCONFIG_EVENT event, DMCONTEXT *dmCtx __attribute__((unused)), void *userdata)
static void generic_Lua_active_notify_callback (DMCONFIG_EVENT event, DMCONTEXT *dmCtx __attribute__((unused)), void *userdata, DIAM_AVPGRP *grp)
static void Lua_init_eval (lua_State *L, char *udata, DMCONTEXT **dmCtx, int *type)
static void Lua_register_eval (lua_State *L, uint32_t code, DMCONTEXT **ctx, LUA_CALLBACK **cb)
static int Lua_generic_shutdown (lua_State *L, const char *udata)
static int Lua_generic_set_sessionid (lua_State *L, const char *udata)
static int Lua_generic_get_sessionid (lua_State *L, const char *udata)
static DIAM_AVPGRP * Lua_build_param_notify_grp (lua_State *L, uint8_t *isActiveNotify)
static void Lua_encode_value (lua_State *L, uint32_t type, const char *path, DIAM_AVPGRP **grp)
static DIAM_AVPGRP * Lua_build_set_grp (lua_State *L)
static DIAM_AVPGRP * Lua_build_get_grp (lua_State *L)
static int Lua_generic_request (lua_State *L, uint32_t code)
static int Lua_generic_register (lua_State *L, uint32_t code)
LUA_SIG (setDebugLevel)
LUA_SIG (init_sequential)
LUA_SIG (init_events)
LUA_SIG (utils_encode_base64)
LUA_SIG (utils_decode_base64)
LUA_SIG_REGISTER (connect)
int luaopen_libluadmconfig (lua_State *L)
static int dmcontext_sequential_gc (lua_State *L)
static int dmcontext_events_gc (lua_State *L)
static int callback_gc (lua_State *L)
LUA_SIG (shutdown)
LUA_SIG_REGISTER (shutdown)
LUA_SIG (set_sessionid)
LUA_SIG_REGISTER (set_sessionid)
LUA_SIG (get_sessionid)
LUA_SIG_REGISTER (get_sessionid)
LUA_SIG (start)
LUA_SIG_REGISTER (start)
LUA_SIG (switch)
LUA_SIG_REGISTER (switch)
LUA_SIG (terminate)
LUA_SIG (get_session_info)
LUA_SIG (get_cfg_session_info)
LUA_SIG (list)
LUA_SIG_REGISTER (list)
LUA_SIG (retrieve_enums)
LUA_SIG_REGISTER (retrieve_enums)
LUA_SIG (param_notify)
LUA_SIG_REGISTER (param_notify)
LUA_SIG (recursive_param_notify)
LUA_SIG_REGISTER (recursive_param_notify)
LUA_SIG (get_passive_notifications)
LUA_SIG_REGISTER (subscribe)
LUA_SIG_REGISTER (unsubscribe)
LUA_SIG (set)
LUA_SIG_REGISTER (set)
LUA_SIG (get)
LUA_SIG_REGISTER (get)
LUA_SIG (add)
LUA_SIG_REGISTER (add)
LUA_SIG (delete)
LUA_SIG_REGISTER (delete)
LUA_SIG (save_config)
LUA_SIG_REGISTER (save_config)
LUA_SIG (restore_config)
LUA_SIG_REGISTER (restore_config)
LUA_SIG (find)
LUA_SIG_REGISTER (find)
LUA_SIG (dump)
LUA_SIG_REGISTER (dump)
Macro Definition Documentation
#define DMCONFIG_CALLBACK_MT
Definition at line 163 of file luawrapper.c.
Referenced by callback_gc(), Lua_register_eval(), LUA_SIG_REGISTER(), and luaopen_libluadmconfig().
#define DMCONFIG_SESSION_EVENTS_MT
Definition at line 162 of file luawrapper.c.
Referenced by dmcontext_events_gc(), Lua_register_eval(), LUA_SIG(), LUA_SIG_REGISTER(), and luaopen_libluadmconfig().
#define DMCONFIG_SESSION_SEQUENTIAL_MT
Definition at line 161 of file luawrapper.c.
Referenced by dmcontext_sequential_gc(), Lua_generic_request(), LUA_SIG(), and luaopen_libluadmconfig().
#define EVENT_BASE_MT
Definition at line 160 of file luawrapper.c.
Referenced by Lua_init_eval().
#define L_SESSIONID
Definition at line 158 of file luawrapper.c.
#define LSTD_FUNC (FNAME, CODE)
Definition at line 2080 of file luawrapper.c.
#define LSTD_FUNC_BOTH (FNAME, CODE)
Definition at line 66 of file luawrapper.c.
#define LSTD_FUNC_REGISTER (FNAME, CODE)
Definition at line 2110 of file luawrapper.c.
#define LUA_HEADER_BOTH (name)
Definition at line 119 of file luawrapper.c.
#define LUA_SIG_REGISTER (name)
Definition at line 63 of file luawrapper.c.
#define NAMETOFUNC_REGISTER (NAME)
Referenced by luaopen_libluadmconfig().
#define PTABLE_ERR ()
Definition at line 1163 of file luawrapper.c.
Referenced by Lua_build_param_notify_grp().
#define TABLE_ERR ()
Definition at line 1544 of file luawrapper.c.
Referenced by Lua_build_get_grp(), and Lua_build_set_grp().
#define TABLE_ERR2 ()
Definition at line 1401 of file luawrapper.c.
Referenced by Lua_encode_value().
Typedef Documentation
typedef struct _Lua_callback LUA_CALLBACK
Function Documentation
static int callback_gc (lua_State * L) static
Definition at line 2158 of file luawrapper.c.
References _Lua_callback::callback_ref, _Lua_callback::callbackDone, _Lua_callback::context_ref, DMCONFIG_CALLBACK_MT, and _Lua_callback::user_data_ref.
Referenced by luaopen_libluadmconfig().
static int dmcontext_events_gc (lua_State * L) static
Definition at line 2146 of file luawrapper.c.
References dm_context_get_socket(), dm_free_requests(), dm_shutdown_socket(), and DMCONFIG_SESSION_EVENTS_MT.
Referenced by luaopen_libluadmconfig().
static int dmcontext_sequential_gc (lua_State * L) static
Definition at line 2134 of file luawrapper.c.
References dm_context_get_socket(), dm_free_requests(), dm_shutdown_socket(), and DMCONFIG_SESSION_SEQUENTIAL_MT.
Referenced by luaopen_libluadmconfig().
static void generic_Lua_active_notify_callback (DMCONFIG_EVENT event, DMCONTEXT *dmCtx __attribute__(unused), void * userdata, DIAM_AVPGRP * grp) static
Definition at line 584 of file luawrapper.c.
References _Lua_callback::callback_ref, _Lua_callback::context_ref, _Lua_callback::L, Lua_decode_notifications(), and _Lua_callback::user_data_ref.
Referenced by LUA_SIG_REGISTER().
static void generic_Lua_callback (DMCONFIG_EVENT event, DMCONTEXT * dmCtx, void * user_data, uint32_t answer_rc, DIAM_AVPGRP * answer_grp) static
Definition at line 477 of file luawrapper.c.
References _Lua_callback::callback_ref, _Lua_callback::callbackDone, CMD_CFGSESSIONINFO, CMD_DB_ADDINSTANCE, CMD_DB_DUMP, CMD_DB_FINDINSTANCE, CMD_DB_GET, CMD_DB_LIST, CMD_DB_RETRIEVE_ENUMS, CMD_ENDSESSION, CMD_GET_PASSIVE_NOTIFICATIONS, CMD_SESSIONINFO, CMD_STARTSESSION, _Lua_callback::code, _Lua_callback::context_ref, dm_context_set_sessionid(), dm_decode_get_cfg_session_info(), dm_decode_start_session(), dm_decode_string(), dm_decode_uint16(), DMCONFIG_ANSWER_READY, flags, _Lua_callback::L, Lua_decode_get(), Lua_decode_get_cfg_session_info(), Lua_decode_get_session_info(), Lua_decode_list(), Lua_decode_notifications(), Lua_decode_retrieve_enums(), and _Lua_callback::user_data_ref.
Referenced by Lua_generic_register(), and LUA_SIG_REGISTER().
static void generic_Lua_connect_callback (DMCONFIG_EVENT event, DMCONTEXT *dmCtx __attribute__(unused), void * userdata) static
Definition at line 562 of file luawrapper.c.
References _Lua_callback::callback_ref, _Lua_callback::callbackDone, _Lua_callback::context_ref, _Lua_callback::L, and _Lua_callback::user_data_ref.
Referenced by LUA_SIG_REGISTER().
static DIAM_AVPGRP * Lua_build_get_grp (lua_State * L) static
Definition at line 1634 of file luawrapper.c.
References AVP_ABSTICKS, AVP_ADDRESS, AVP_BINARY, AVP_BOOL, AVP_COUNTER, AVP_DATE, AVP_ENUM, AVP_ENUMID, AVP_INT32, AVP_INT64, AVP_PATH, AVP_RELTICKS, AVP_STRING, AVP_TYPE_PATH, AVP_UINT32, AVP_UINT64, AVP_UNKNOWN, diam_avpgrp_add_uint32_string(), dm_grp_new(), TABLE_ERR, and VP_TRAVELPING.
Referenced by LUA_SIG(), and LUA_SIG_REGISTER().
static DIAM_AVPGRP * Lua_build_param_notify_grp (lua_State * L, uint8_t * isActiveNotify) static
Definition at line 1169 of file luawrapper.c.
References dm_grp_new(), dm_grp_param_notify(), and PTABLE_ERR.
Referenced by LUA_SIG(), and LUA_SIG_REGISTER().
static DIAM_AVPGRP * Lua_build_set_grp (lua_State * L) static
Definition at line 1550 of file luawrapper.c.
References dm_grp_new(), Lua_encode_value(), and TABLE_ERR.
Referenced by LUA_SIG(), and LUA_SIG_REGISTER().
static uint32_t Lua_decode_get (lua_State * L, DIAM_AVPGRP * answer) static
Definition at line 217 of file luawrapper.c.
References diam_avpgrp_get_avp(), flags, Lua_decode_unknown(), RC_OK, and vendor_id.
Referenced by generic_Lua_callback(), and LUA_SIG().
static uint32_t Lua_decode_get_cfg_session_info (lua_State * L, uint32_t sessionid, uint32_t flags, struct timeval timeout) static
Definition at line 180 of file luawrapper.c.
References RC_OK.
Referenced by generic_Lua_callback(), and LUA_SIG().
static uint32_t Lua_decode_get_session_info (lua_State * L, DIAM_AVPGRP * answer) static
Definition at line 166 of file luawrapper.c.
References dm_decode_get_session_info(), flags, and RC_OK.
Referenced by generic_Lua_callback(), and LUA_SIG().
static uint32_t Lua_decode_list (lua_State * L, DIAM_AVPGRP * grp, int * nodes) static
Definition at line 248 of file luawrapper.c.
References AVP_CONTAINER, AVP_NODE_DATATYPE, AVP_NODE_NAME, AVP_NODE_SIZE, AVP_NODE_TYPE, code, diam_avpgrp_get_avp(), diam_decode_avpgrp(), diam_get_uint32_avp(), dm_grp_free(), flags, Lua_decode_unknown(), NODE_OBJECT, NODE_PARAMETER, NODE_TABLE, RC_ERR_ALLOC, RC_ERR_MISC, RC_OK, and vendor_id.
Referenced by generic_Lua_callback(), and LUA_SIG().
static uint32_t Lua_decode_notifications (lua_State * L, DIAM_AVPGRP * answer) static
Definition at line 402 of file luawrapper.c.
References diam_avpgrp_get_avp(), dm_decode_instance_created(), dm_decode_instance_deleted(), dm_decode_notifications(), dm_decode_parameter_changed(), dm_grp_free(), flags, Lua_decode_unknown(), NOTIFY_INSTANCE_CREATED, NOTIFY_INSTANCE_DELETED, NOTIFY_NOTHING, NOTIFY_PARAMETER_CHANGED, RC_ERR_MISC, and vendor_id.
Referenced by generic_Lua_active_notify_callback(), generic_Lua_callback(), and LUA_SIG().
static uint32_t Lua_decode_retrieve_enums (lua_State * L, DIAM_AVPGRP * answer) static
Definition at line 384 of file luawrapper.c.
References dm_decode_enumval(), RC_ERR_MISC, and RC_OK.
Referenced by generic_Lua_callback(), and LUA_SIG().
static uint32_t Lua_decode_unknown (lua_State * L, uint32_t type, void * data, size_t len) static
Definition at line 195 of file luawrapper.c.
References AVP_BINARY, dm_decode_unknown_as_string(), and RC_OK.
Referenced by Lua_decode_get(), Lua_decode_list(), and Lua_decode_notifications().
static void Lua_encode_value (lua_State * L, uint32_t type, const char * path, DIAM_AVPGRP ** grp) static
Definition at line 1407 of file luawrapper.c.
References AVP_ABSTICKS, AVP_ADDRESS, AVP_BINARY, AVP_BOOL, AVP_DATE, AVP_ENUM, AVP_ENUMID, AVP_INT32, AVP_INT64, AVP_PATH, AVP_RELTICKS, AVP_STRING, AVP_UINT32, AVP_UINT64, AVP_UNKNOWN, dm_grp_set(), dm_grp_set_addr(), dm_grp_set_binary(), dm_grp_set_bool(), dm_grp_set_date(), dm_grp_set_enum(), dm_grp_set_enumid(), dm_grp_set_int32(), dm_grp_set_path(), dm_grp_set_string(), dm_grp_set_uint32(), dm_grp_set_uint64(), dm_grp_set_unknown(), htonll, and TABLE_ERR2.
Referenced by Lua_build_set_grp(), LUA_SIG(), and LUA_SIG_REGISTER().
static int Lua_generic_get_sessionid (lua_State * L, const char * udata) static
Definition at line 799 of file luawrapper.c.
References dm_context_get_sessionid(), and RC_OK.
Referenced by LUA_SIG(), and LUA_SIG_REGISTER().
static int Lua_generic_register (lua_State * L, uint32_t code) static
Definition at line 2087 of file luawrapper.c.
References dm_generic_register_request(), generic_Lua_callback(), and Lua_register_eval().
static int Lua_generic_request (lua_State * L, uint32_t code) static
Definition at line 2068 of file luawrapper.c.
References dm_generic_send_request(), and DMCONFIG_SESSION_SEQUENTIAL_MT.
static int Lua_generic_set_sessionid (lua_State * L, const char * udata) static
Definition at line 768 of file luawrapper.c.
References dm_context_set_sessionid(), and RC_OK.
Referenced by LUA_SIG(), and LUA_SIG_REGISTER().
static int Lua_generic_shutdown (lua_State * L, const char * udata) static
Definition at line 741 of file luawrapper.c.
References dm_context_set_socket(), dm_shutdown_socket(), and RC_OK.
Referenced by LUA_SIG(), and LUA_SIG_REGISTER().
static void Lua_init_eval (lua_State * L, char * udata, DMCONTEXT ** dmCtx, int * type) static
Definition at line 604 of file luawrapper.c.
References dm_context_init(), and EVENT_BASE_MT.
Referenced by LUA_SIG().
static void Lua_register_eval (lua_State * L, uint32_t code, DMCONTEXT ** ctx, LUA_CALLBACK ** cb) static
Definition at line 675 of file luawrapper.c.
References code, DMCONFIG_CALLBACK_MT, and DMCONFIG_SESSION_EVENTS_MT.
Referenced by Lua_generic_register(), and LUA_SIG_REGISTER().
LUA_SIG (setDebugLevel)
Definition at line 663 of file luawrapper.c.
References dmconfig_debug_level.
LUA_SIG (init_sequential)
Definition at line 631 of file luawrapper.c.
References dm_init_socket(), DMCONFIG_SESSION_SEQUENTIAL_MT, and Lua_init_eval().
LUA_SIG (init_events)
Definition at line 647 of file luawrapper.c.
References dm_create_socket(), DMCONFIG_SESSION_EVENTS_MT, and Lua_init_eval().
LUA_SIG (utils_encode_base64)
Definition at line 2179 of file luawrapper.c.
References RC_ERR_ALLOC, and RC_OK.
LUA_SIG (utils_decode_base64)
Definition at line 2203 of file luawrapper.c.
References RC_ERR_ALLOC, and RC_OK.
LUA_SIG (shutdown)
Definition at line 757 of file luawrapper.c.
References DMCONFIG_SESSION_SEQUENTIAL_MT, and Lua_generic_shutdown().
LUA_SIG (set_sessionid)
Definition at line 788 of file luawrapper.c.
References DMCONFIG_SESSION_SEQUENTIAL_MT, and Lua_generic_set_sessionid().
LUA_SIG (get_sessionid)
Definition at line 818 of file luawrapper.c.
References DMCONFIG_SESSION_SEQUENTIAL_MT, and Lua_generic_get_sessionid().
LUA_SIG (start)
Definition at line 828 of file luawrapper.c.
References CMD_FLAG_READWRITE, dm_send_start_session(), and DMCONFIG_SESSION_SEQUENTIAL_MT.
LUA_SIG (switch)
Definition at line 911 of file luawrapper.c.
References CMD_FLAG_READWRITE, dm_send_switch_session(), and DMCONFIG_SESSION_SEQUENTIAL_MT.
LUA_SIG (terminate)
Definition at line 993 of file luawrapper.c.
References dm_send_end_session(), and DMCONFIG_SESSION_SEQUENTIAL_MT.
LUA_SIG (get_session_info)
Definition at line 1006 of file luawrapper.c.
References CMD_SESSIONINFO, dm_generic_send_request(), dm_grp_free(), DMCONFIG_SESSION_SEQUENTIAL_MT, and Lua_decode_get_session_info().
LUA_SIG (get_cfg_session_info)
Definition at line 1030 of file luawrapper.c.
References dm_send_get_cfg_session_info(), DMCONFIG_SESSION_SEQUENTIAL_MT, flags, and Lua_decode_get_cfg_session_info().
LUA_SIG (list)
Definition at line 1053 of file luawrapper.c.
References dm_grp_free(), dm_send_list(), DMCONFIG_SESSION_SEQUENTIAL_MT, and Lua_decode_list().
LUA_SIG (retrieve_enums)
Definition at line 1110 of file luawrapper.c.
References dm_grp_free(), dm_send_retrieve_enums(), DMCONFIG_SESSION_SEQUENTIAL_MT, and Lua_decode_retrieve_enums().
LUA_SIG (param_notify)
Definition at line 1205 of file luawrapper.c.
References dm_grp_free(), dm_send_packet_param_notify(), DMCONFIG_SESSION_SEQUENTIAL_MT, and Lua_build_param_notify_grp().
LUA_SIG (recursive_param_notify)
Definition at line 1255 of file luawrapper.c.
References dm_send_recursive_param_notify(), and DMCONFIG_SESSION_SEQUENTIAL_MT.
LUA_SIG (get_passive_notifications)
Definition at line 1303 of file luawrapper.c.
References dm_grp_free(), dm_send_get_passive_notifications(), DMCONFIG_SESSION_SEQUENTIAL_MT, and Lua_decode_notifications().
LUA_SIG (set)
Definition at line 1591 of file luawrapper.c.
References dm_grp_free(), dm_send_packet_set(), DMCONFIG_SESSION_SEQUENTIAL_MT, and Lua_build_set_grp().
LUA_SIG (get)
Definition at line 1700 of file luawrapper.c.
References dm_grp_free(), dm_send_packet_get(), DMCONFIG_SESSION_SEQUENTIAL_MT, Lua_build_get_grp(), and Lua_decode_get().
LUA_SIG (add)
Definition at line 1752 of file luawrapper.c.
References DM_ADD_INSTANCE_AUTO, dm_send_add_instance(), and DMCONFIG_SESSION_SEQUENTIAL_MT.
LUA_SIG (delete)
Definition at line 1807 of file luawrapper.c.
References dm_send_del_instance(), and DMCONFIG_SESSION_SEQUENTIAL_MT.
LUA_SIG (save_config)
Definition at line 1850 of file luawrapper.c.
References dm_send_cmd_conf_save(), and DMCONFIG_SESSION_SEQUENTIAL_MT.
LUA_SIG (restore_config)
Definition at line 1893 of file luawrapper.c.
References dm_send_cmd_conf_restore(), and DMCONFIG_SESSION_SEQUENTIAL_MT.
LUA_SIG (find)
Definition at line 1936 of file luawrapper.c.
References dm_grp_free(), dm_grp_new(), dm_send_find_instance(), DMCONFIG_SESSION_SEQUENTIAL_MT, Lua_encode_value(), and RC_ERR_ALLOC.
LUA_SIG (dump)
Definition at line 2010 of file luawrapper.c.
References dm_send_cmd_dump(), and DMCONFIG_SESSION_SEQUENTIAL_MT.
LUA_SIG_REGISTER (connect)
Definition at line 708 of file luawrapper.c.
References dm_register_connect_callback(), generic_Lua_connect_callback(), and Lua_register_eval().
LUA_SIG_REGISTER (shutdown)
Definition at line 762 of file luawrapper.c.
References DMCONFIG_SESSION_EVENTS_MT, and Lua_generic_shutdown().
LUA_SIG_REGISTER (set_sessionid)
Definition at line 793 of file luawrapper.c.
References DMCONFIG_SESSION_EVENTS_MT, and Lua_generic_set_sessionid().
LUA_SIG_REGISTER (get_sessionid)
Definition at line 823 of file luawrapper.c.
References DMCONFIG_SESSION_EVENTS_MT, and Lua_generic_get_sessionid().
LUA_SIG_REGISTER (start)
Definition at line 862 of file luawrapper.c.
References CMD_FLAG_READWRITE, CMD_STARTSESSION, dm_register_start_session(), flags, generic_Lua_callback(), and Lua_register_eval().
LUA_SIG_REGISTER (switch)
Definition at line 944 of file luawrapper.c.
References CMD_FLAG_READWRITE, CMD_SWITCHSESSION, dm_register_switch_session(), flags, generic_Lua_callback(), and Lua_register_eval().
LUA_SIG_REGISTER (list)
Definition at line 1081 of file luawrapper.c.
References CMD_DB_LIST, dm_register_list(), generic_Lua_callback(), and Lua_register_eval().
LUA_SIG_REGISTER (retrieve_enums)
Definition at line 1137 of file luawrapper.c.
References CMD_DB_RETRIEVE_ENUMS, dm_register_retrieve_enums(), generic_Lua_callback(), and Lua_register_eval().
LUA_SIG_REGISTER (param_notify)
Definition at line 1228 of file luawrapper.c.
References CMD_PARAM_NOTIFY, dm_grp_free(), dm_register_packet_param_notify(), generic_Lua_callback(), Lua_build_param_notify_grp(), and Lua_register_eval().
LUA_SIG_REGISTER (recursive_param_notify)
Definition at line 1273 of file luawrapper.c.
References CMD_RECURSIVE_PARAM_NOTIFY, dm_register_recursive_param_notify(), generic_Lua_callback(), and Lua_register_eval().
LUA_SIG_REGISTER (subscribe)
Definition at line 1326 of file luawrapper.c.
References _Lua_callback::callback_ref, _Lua_callback::callbackDone, CMD_SUBSCRIBE_NOTIFY, _Lua_callback::code, _Lua_callback::context_ref, dm_register_subscribe_notify(), DMCONFIG_CALLBACK_MT, generic_Lua_active_notify_callback(), generic_Lua_callback(), _Lua_callback::L, Lua_register_eval(), and _Lua_callback::user_data_ref.
LUA_SIG_REGISTER (unsubscribe)
Definition at line 1368 of file luawrapper.c.
References dmContext::_dmContext_callbacks::active_notification, _Lua_callback::callback_ref, _Lua_callback::callbackDone, dmContext::callbacks, CMD_UNSUBSCRIBE_NOTIFY, _Lua_callback::context_ref, dm_register_unsubscribe_notify(), generic_Lua_callback(), Lua_register_eval(), RC_ERR_MISC, dmContext::_dmContext_callbacks::_callback_active_notification::user_data, and _Lua_callback::user_data_ref.
LUA_SIG_REGISTER (set)
Definition at line 1608 of file luawrapper.c.
References CMD_DB_SET, dm_grp_free(), dm_register_packet_set(), generic_Lua_callback(), Lua_build_set_grp(), and Lua_register_eval().
LUA_SIG_REGISTER (get)
Definition at line 1726 of file luawrapper.c.
References CMD_DB_GET, dm_grp_free(), dm_register_packet_get(), generic_Lua_callback(), Lua_build_get_grp(), and Lua_register_eval().
LUA_SIG_REGISTER (add)
Definition at line 1776 of file luawrapper.c.
References CMD_DB_ADDINSTANCE, DM_ADD_INSTANCE_AUTO, dm_register_add_instance(), generic_Lua_callback(), and Lua_register_eval().
LUA_SIG_REGISTER (delete)
Definition at line 1824 of file luawrapper.c.
References CMD_DB_DELINSTANCE, dm_register_del_instance(), generic_Lua_callback(), and Lua_register_eval().
LUA_SIG_REGISTER (save_config)
Definition at line 1867 of file luawrapper.c.
References CMD_DEV_CONF_SAVE, dm_register_cmd_conf_save(), generic_Lua_callback(), and Lua_register_eval().
LUA_SIG_REGISTER (restore_config)
Definition at line 1910 of file luawrapper.c.
References CMD_DEV_CONF_RESTORE, dm_register_cmd_conf_save(), generic_Lua_callback(), and Lua_register_eval().
LUA_SIG_REGISTER (find)
Definition at line 1970 of file luawrapper.c.
References CMD_DB_FINDINSTANCE, dm_grp_free(), dm_grp_new(), dm_register_find_instance(), generic_Lua_callback(), Lua_encode_value(), Lua_register_eval(), and RC_ERR_ALLOC.
LUA_SIG_REGISTER (dump)
Definition at line 2036 of file luawrapper.c.
References CMD_DB_DUMP, dm_register_cmd_dump(), generic_Lua_callback(), and Lua_register_eval().
int luaopen_libluadmconfig (lua_State * L)
Definition at line 2229 of file luawrapper.c.
References callback_gc(), CMD_FLAG_CONFIGURE, CMD_FLAG_READWRITE, DM_ADD_INSTANCE_AUTO, DMCONFIG_ANSWER_READY, DMCONFIG_CALLBACK_MT, DMCONFIG_CONNECTED, DMCONFIG_ERROR_CONNECTING, DMCONFIG_ERROR_READING, DMCONFIG_ERROR_WRITING, DMCONFIG_SESSION_EVENTS_MT, DMCONFIG_SESSION_SEQUENTIAL_MT, dmcontext_events_gc(), dmcontext_sequential_gc(), NAMETOFUNC_REGISTER, NOTIFY_INSTANCE_CREATED, NOTIFY_INSTANCE_DELETED, NOTIFY_NOTHING, NOTIFY_PARAMETER_CHANGED, RC_ERR_ALLOC, RC_ERR_CANNOT_OPEN_CFGSESSION, RC_ERR_CANNOT_SUBSCRIBE_NOTIFY, RC_ERR_CONNECTION, RC_ERR_HOSTNAME_RESOLUTION, RC_ERR_INVALID_SESSIONID, RC_ERR_MISC, RC_ERR_OPERATION_IN_PROGRESS, RC_ERR_REQUIRES_CFGSESSION, RC_ERR_REQUIRES_NOTIFY, RC_ERR_TIMEOUT, and RC_OK.