/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/*
 * WARNING: This file has been autogenerated by tablegen/deps.pl
 *
 *            !!! DO NOT MODIFY MANUALLY !!!
 */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "dm_token.h"
#include "dm_action.h"
#include "dm_action_table.h"


const struct dm_action *dm_actions[] = {
};
