/*
 *    __                        __      _
 *   / /__________ __   _____  / /___  (_)___  ____ _
 *  / __/ ___/ __ `/ | / / _ \/ / __ \/ / __ \/ __ `/
 * / /_/ /  / /_/ /| |/ /  __/ / /_/ / / / / / /_/ /
 * \__/_/   \__,_/ |___/\___/_/ .___/_/_/ /_/\__, /
 *                           /_/            /____/
 *
 * (c) Travelping GmbH <info@travelping.com>
 *
 */

/*
 * WARNING: This file has been autogenerated by tablegen/deps.pl
 *
 *            !!! DO NOT MODIFY MANUALLY !!!
 */

#ifndef __DM_ACTION_TABLE_H
#define __DM_ACTION_TABLE_H

enum dm_actions {
	DM_NONE,
};

#endif
