/*
 *    __                        __      _
 *   / /__________ __   _____  / /___  (_)___  ____ _
 *  / __/ ___/ __ `/ | / / _ \/ / __ \/ / __ \/ __ `/
 * / /_/ /  / /_/ /| |/ /  __/ / /_/ / / / / / /_/ /
 * \__/_/   \__,_/ |___/\___/_/ .___/_/_/ /_/\__, /
 *                           /_/            /____/
 *
 * (c) Travelping GmbH <info@travelping.com>
 *
 */

/*
 * WARNING: This file has been autogenerated by tablegen/deps.pl
 *
 *            !!! DO NOT MODIFY MANUALLY !!!
 */

static const char *t_actions[] = {
	type_map_init(DM_NONE),
};
