/*
 *    __                        __      _
 *   / /__________ __   _____  / /___  (_)___  ____ _
 *  / __/ ___/ __ `/ | / / _ \/ / __ \/ / __ \/ __ `/
 * / /_/ /  / /_/ /| |/ /  __/ / /_/ / / / / / /_/ /
 * \__/_/   \__,_/ |___/\___/_/ .___/_/_/ /_/\__, /
 *                           /_/            /____/
 *
 * (c) Travelping GmbH <info@travelping.com>
 *
 */

/*
 * WARNING: This file has been autogenerated by tablegen/deps.pl
 *
 *            !!! DO NOT MODIFY MANUALLY !!!
 */

static const char *t_actions[] = {
	type_map_init(DM_NONE),
	type_map_init(DM_LAN_RECONF),
	type_map_init(DM_ZONE),
	type_map_init(DM_DEV_REV_CHNG),
	type_map_init(DM_CHECK_NTPD),
	type_map_init(DM_SCG_CLASS),
	type_map_init(DM_RESTART_SYSLOG),
	type_map_init(DM_RELAY),
	type_map_init(DM_WAN_RECONF),
	type_map_init(DM_HTTPD_RESTART),
	type_map_init(DM_RAD_SRV),
	type_map_init(DM_L2TP_RECONF),
	type_map_init(DM_ZONE_RAD_SRV),
	type_map_init(DM_HTTPD_RELOAD),
	type_map_init(DM_CHANGE_HNAME),
	type_map_init(DM_L3_RELOAD),
	type_map_init(DM_CLNT_TIMER_REARM),
	type_map_init(DM_L2TP_RELAY),
	type_map_init(DM_L3POLICY),
	type_map_init(DM_FIREWALL),
	type_map_init(DM_SCG_ACL),
	type_map_init(DM_PROXY),
	type_map_init(DM_RESTART_SNMPD),
};
