/*
 *    __                        __      _
 *   / /__________ __   _____  / /___  (_)___  ____ _
 *  / __/ ___/ __ `/ | / / _ \/ / __ \/ / __ \/ __ `/
 * / /_/ /  / /_/ /| |/ /  __/ / /_/ / / / / / /_/ /
 * \__/_/   \__,_/ |___/\___/_/ .___/_/_/ /_/\__, /
 *                           /_/            /____/
 *
 * (c) Travelping GmbH <info@travelping.com>
 *
 */

/*
 * WARNING: This file has been autogenerated by tablegen/deps.pl
 *
 *            !!! DO NOT MODIFY MANUALLY !!!
 */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "tr069_token.h"
#include "tr069_action.h"
#include "tr069_action_table.h"

#include "firewall.h"
#include "ifup.h"
#include "snmpd.h"
#include "client.h"
#include "dhcp.h"
#include "session.h"
#include "l3forward.h"
#include "radius.h"
#include "lng.h"

static struct tr069_action dm_zone = {
	.sel_len = 4,

	.pre = NULL,
	.action = dm_zone_action,
	.post = NULL,

	.chain_cnt = 2,
	.chain = { DM_L3POLICY, DM_FIREWALL, },
};

/* WARN: look out for vaild selector length */
static struct tr069_action dm_lan_reconf = {
	.sel_len = 3,

	.pre = NULL,
	.action = dm_lan_reconf_action,
	.post = NULL,

	.chain_cnt = 1,
	.chain = { DM_HTTPD_RELOAD, },
};

/* meta action */
static struct tr069_action dm_scg_class = {
	.sel_len = 1,

	.pre = NULL,
	.action = NULL,
	.post = NULL,

	.chain_cnt = 2,
	.chain = { DM_L3POLICY, DM_FIREWALL, },
};

/* INFO: the selector will not be used during callback */
static struct tr069_action dm_check_ntpd = {
	.sel_len = 2,

	.pre = NULL,
	.action = dm_check_ntpd_action,
	.post = NULL,

	.chain_cnt = 0,
};

static struct tr069_action dm_dev_rev_chng = {
	.sel_len = 7,

	.pre = NULL,
	.action = dm_dev_rev_chng_action,
	.post = NULL,

	.chain_cnt = 0,
};

/* INFO: the selector will not be used during callback */
static struct tr069_action dm_restart_syslog = {
	.sel_len = 3,

	.pre = NULL,
	.action = dm_restart_syslog_action,
	.post = NULL,

	.chain_cnt = 0,
};

/* WARN: look out for vaild selector length */
static struct tr069_action dm_wan_reconf = {
	.sel_len = 5,

	.pre = NULL,
	.action = dm_wan_reconf_action,
	.post = NULL,

	.chain_cnt = 1,
	.chain = { DM_HTTPD_RELOAD, },
};

static struct tr069_action dm_httpd_restart = {
	.sel_len = 1,

	.pre = NULL,
	.action = dm_httpd_restart_action,
	.post = NULL,

	.chain_cnt = 0,
};

static struct tr069_action dm_rad_srv = {
	.sel_len = 6,

	.pre = NULL,
	.action = dm_rad_srv_action,
	.post = NULL,

	.chain_cnt = 0,
};

static struct tr069_action dm_zone_rad_srv = {
	.sel_len = 7,

	.pre = NULL,
	.action = dm_zone_rad_srv_action,
	.post = NULL,

	.chain_cnt = 0,
};

static struct tr069_action dm_change_hname = {
	.sel_len = 3,

	.pre = NULL,
	.action = dm_change_hname_action,
	.post = NULL,

	.chain_cnt = 0,
};

static struct tr069_action dm_l3_reload = {
	.sel_len = 4,

	.pre = NULL,
	.action = dm_l3_reload_action,
	.post = NULL,

	.chain_cnt = 0,
};

static struct tr069_action dm_clnt_timer_rearm = {
	.sel_len = 7,

	.pre = NULL,
	.action = dm_clnt_timer_rearm_action,
	.post = NULL,

	.chain_cnt = 0,
};

/* meta action: L2TP/LNG values also affecting DHCP relaying */
static struct tr069_action dm_l2tp_relay = {
	.sel_len = 2,

	.pre = NULL,
	.action = NULL,
	.post = NULL,

	.chain_cnt = 2,
	.chain = { DM_RELAY, DM_L2TP_RECONF, },
};

/* INFO: the selector will not be used during callback */
static struct tr069_action dm_restart_snmpd = {
	.sel_len = 2,

	.pre = NULL,
	.action = dm_restart_snmpd_action,
	.post = NULL,

	.chain_cnt = 0,
};

static struct tr069_action dm_relay = {
	.sel_len = 2,

	.pre = NULL,
	.action = dm_relay_action,
	.post = NULL,

	.chain_cnt = 0,
};

/* INFO: the selector will not be used during callback */
static struct tr069_action dm_l2tp_reconf = {
	.sel_len = 2,

	.pre = NULL,
	.action = dm_l2tp_reconf_action,
	.post = NULL,

	.chain_cnt = 0,
};

static struct tr069_action dm_httpd_reload = {
	.sel_len = 1,

	.pre = NULL,
	.action = dm_httpd_reload_action,
	.post = NULL,

	.chain_cnt = 0,
};

static struct tr069_action dm_l3policy = {
	.sel_len = 4,

	.pre = NULL,
	.action = dm_l3policy_action,
	.post = NULL,

	.chain_cnt = 0,
};

static struct tr069_action dm_firewall = {
	.sel_len = 2,

	.pre = NULL,
	.action = dm_firewall_action,
	.post = NULL,

	.chain_cnt = 2,
	.chain = { DM_SCG_ACL, DM_PROXY, },
};

static struct tr069_action dm_scg_acl = {
	.sel_len = 2,

	.pre = NULL,
	.action = dm_scg_acl_action,
	.post = NULL,

	.chain_cnt = 0,
};

static struct tr069_action dm_proxy = {
	.sel_len = 2,

	.pre = NULL,
	.action = dm_proxy_action,
	.post = NULL,

	.chain_cnt = 0,
};

const struct tr069_action *dm_actions[] = {
	[DM_ZONE] = &dm_zone,
	[DM_LAN_RECONF] = &dm_lan_reconf,
	[DM_SCG_CLASS] = &dm_scg_class,
	[DM_CHECK_NTPD] = &dm_check_ntpd,
	[DM_DEV_REV_CHNG] = &dm_dev_rev_chng,
	[DM_RESTART_SYSLOG] = &dm_restart_syslog,
	[DM_WAN_RECONF] = &dm_wan_reconf,
	[DM_HTTPD_RESTART] = &dm_httpd_restart,
	[DM_RAD_SRV] = &dm_rad_srv,
	[DM_ZONE_RAD_SRV] = &dm_zone_rad_srv,
	[DM_CHANGE_HNAME] = &dm_change_hname,
	[DM_L3_RELOAD] = &dm_l3_reload,
	[DM_CLNT_TIMER_REARM] = &dm_clnt_timer_rearm,
	[DM_L2TP_RELAY] = &dm_l2tp_relay,
	[DM_RESTART_SNMPD] = &dm_restart_snmpd,
	[DM_RELAY] = &dm_relay,
	[DM_L2TP_RECONF] = &dm_l2tp_reconf,
	[DM_HTTPD_RELOAD] = &dm_httpd_reload,
	[DM_L3POLICY] = &dm_l3policy,
	[DM_FIREWALL] = &dm_firewall,
	[DM_SCG_ACL] = &dm_scg_acl,
	[DM_PROXY] = &dm_proxy,
};
