/*
 *    __                        __      _
 *   / /__________ __   _____  / /___  (_)___  ____ _
 *  / __/ ___/ __ `/ | / / _ \/ / __ \/ / __ \/ __ `/
 * / /_/ /  / /_/ /| |/ /  __/ / /_/ / / / / / /_/ /
 * \__/_/   \__,_/ |___/\___/_/ .___/_/_/ /_/\__, /
 *                           /_/            /____/
 *
 * (c) Travelping GmbH <info@travelping.com>
 *
 */

/*
 * WARNING: This file has been autogenerated by tablegen/deps.pl
 *
 *            !!! DO NOT MODIFY MANUALLY !!!
 */

#ifndef __TR069_ACTION_TABLE_H
#define __TR069_ACTION_TABLE_H

enum dm_actions {
	DM_NONE,
	DM_ZONE,
	DM_LAN_RECONF,
	DM_SCG_CLASS,
	DM_CHECK_NTPD,
	DM_DEV_REV_CHNG,
	DM_RESTART_SYSLOG,
	DM_WAN_RECONF,
	DM_HTTPD_RESTART,
	DM_RAD_SRV,
	DM_ZONE_RAD_SRV,
	DM_CHANGE_HNAME,
	DM_L3_RELOAD,
	DM_CLNT_TIMER_REARM,
	DM_L2TP_RELAY,
	DM_RESTART_SNMPD,
	DM_RELAY,
	DM_L2TP_RECONF,
	DM_HTTPD_RELOAD,
	DM_L3POLICY,
	DM_FIREWALL,
	DM_SCG_ACL,
	DM_PROXY,
};

#endif
