/*
 * WARNING: This file has been autogenerated by tablegen/deps.pl
 *
 *            !!! DO NOT MODIFY MANUALLY !!!
 */

enum {
	DM_NONE,
	DM_HTTPD_RELOAD,
	DM_LAN_RECONF,
	DM_ZONE,
	DM_CHANGE_HNAME,
	DM_CHECK_NTPD,
	DM_L3_RELOAD,
	DM_RESTART_SYSLOG,
	DM_WAN_RECONF,
	DM_FIREWALL,
	DM_DHCP_COND,
	DM_SCG_ACL,
	DM_PROXY,
	DM_RESTART_SNMPD,
	DM_ZONE_RAD_SRV,
};

const char *t_actions[] = {
	type_map_init(DM_NONE),
	type_map_init(DM_HTTPD_RELOAD),
	type_map_init(DM_LAN_RECONF),
	type_map_init(DM_ZONE),
	type_map_init(DM_CHANGE_HNAME),
	type_map_init(DM_CHECK_NTPD),
	type_map_init(DM_L3_RELOAD),
	type_map_init(DM_RESTART_SYSLOG),
	type_map_init(DM_WAN_RECONF),
	type_map_init(DM_FIREWALL),
	type_map_init(DM_DHCP_COND),
	type_map_init(DM_SCG_ACL),
	type_map_init(DM_PROXY),
	type_map_init(DM_RESTART_SNMPD),
	type_map_init(DM_ZONE_RAD_SRV),
};

struct string_map action_map[] = {
	{ "change_hname", DM_CHANGE_HNAME },
	{ "check_ntpd", DM_CHECK_NTPD },
	{ "dhcp_cond", DM_DHCP_COND },
	{ "firewall", DM_FIREWALL },
	{ "httpd_reload", DM_HTTPD_RELOAD },
	{ "l3_reload", DM_L3_RELOAD },
	{ "lan_reconf", DM_LAN_RECONF },
	{ "proxy", DM_PROXY },
	{ "restart_snmpd", DM_RESTART_SNMPD },
	{ "restart_syslog", DM_RESTART_SYSLOG },
	{ "scg_acl", DM_SCG_ACL },
	{ "wan_reconf", DM_WAN_RECONF },
	{ "zone", DM_ZONE },
	{ "zone_rad_srv", DM_ZONE_RAD_SRV },
};

