<?xml version="1.0"?>

<!--
       __                        __      _
      / /__________ __   _____  / /___  (_)___  ____ _
     / __/ ___/ __ `/ | / / _ \/ / __ \/ / __ \/ __ `/
    / /_/ /  / /_/ /| |/ /  __/ / /_/ / / / / / /_/ /
    \__/_/   \__,_/ |___/\___/_/ .___/_/_/ /_/\__, /
                              /_/            /____/

    (c) Travelping GmbH <info@travelping.com>

-->

<stylesheet version="1.0"
	    xmlns="http://www.w3.org/1999/XSL/Transform"
	    xmlns:str="http://exslt.org/strings">
	<output method="text"/>

	<variable name="lower">abcdefghijklmnopqrstuvwxyz-</variable>
	<variable name="upper">ABCDEFGHIJKLMNOPQRSTUVWXYZ_</variable>

	<template name="Comment">
		<param name="str"/>
		<value-of select="concat('/* ', $str, ' */&#xA;')"/>
	</template>

	<template name="Constant">
		<param name="name"/>
		<param name="value"/>

		<variable name="define" select="concat('#define ', translate($name, $lower, $upper))"/>
		<value-of select="concat($define, str:padding(40 - string-length($define)), $value, '&#xA;')"/>
	</template>

	<template match="/">
		<call-template name="Comment">
			<with-param name="str">WARNING: FILE AUTOGENERATED FROM DMCONFIG.XML !!!</with-param>
		</call-template>

		<text>&#xA;</text>
		<text>#ifndef __CODES_H&#xA;</text>
		<text>#define __CODES_H&#xA;</text>
		<text>&#xA;</text>

		<apply-templates select="dictionary/vendor"/>
		<text>&#xA;</text>
		<apply-templates select="dictionary/application[@name = 'dmconfig']"/>
		<text>&#xA;</text>
		<apply-templates select="dictionary/base/command"/>
		<text>&#xA;</text>
		<!-- ignore dummy AVP spec -->
		<apply-templates select="dictionary/base/avp[@name != 'AVP']"/>

		<text>&#xA;</text>
		<text>#endif&#xA;</text>
	</template>

	<template match="vendor">
		<call-template name="Comment">
			<with-param name="str" select="@description"/>
		</call-template>

		<call-template name="Constant">
			<with-param name="name" select="concat('VP-', @name)"/>
			<with-param name="value" select="@id"/>
		</call-template>
	</template>

	<template match="application[1]">
		<call-template name="Comment">
			<with-param name="str" select="@name"/>
		</call-template>

		<call-template name="Constant">
			<with-param name="name">App-Id</with-param>
			<with-param name="value" select="@id"/>
		</call-template>
	</template>

	<template match="command">
		<call-template name="Constant">
			<with-param name="name" select="concat('Cmd-', @name)"/>
			<with-param name="value" select="@code"/>
		</call-template>
	</template>

	<template match="avp">
		<call-template name="Constant">
			<with-param name="name" select="concat('AVP-', @name)"/>
			<with-param name="value" select="@code"/>
		</call-template>

		<if test="enum">
			<text>typedef enum {&#xA;</text>

			<for-each select="enum">
				<sort data-type="number" select="@code"/>

				<variable name="enum" select="concat(str:padding(8), translate(@name, $lower, $upper))"/>
				<value-of select="concat($enum, str:padding(40 - string-length($enum)), '= ', @code)"/>
				<if test="position() != last()">,</if>
				<text>&#xA;</text>
			</for-each>

			<value-of select="concat('} AVP_', translate(@name, $lower, $upper), '_e;&#xA;')"/>
		</if>
	</template>
</stylesheet>

