
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. 
 *
 *
 * WARNING: This file has been autogenerated by yang/pyang_plugin/OpenCPE.py
 *
 *            !!! DO NOT MODIFY MANUALLY !!!
*/ 

static const char *t_actions[] = { 
    type_map_init(DM_NONE),
    type_map_init(DM_NTP),
    type_map_init(DM_DNS),
    type_map_init(DM_IF_IP),
    type_map_init(DM_IF_NEIGH),
};

