
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. 
 *
 *
 * WARNING: This file has been autogenerated by yang/pyang_plugin/OpenCPE.py
 *
 *            !!! DO NOT MODIFY MANUALLY !!!
*/ 


#ifndef __DM_ACTION_TABLE_H
#define __DM_ACTION_TABLE_H

enum dm_actions { 
    DM_NONE,
    DM_NTP,
    DM_DNS,
    DM_IF_IP,
    DM_IF_NEIGH,
};

#endif
