/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.9 2005/01/07 09:37:18 dts12 Exp $
 */

#include <stdio.h>
#include <netinet/in.h>
#include <sys/types.h>
#include <sys/time.h>

#include "tr069/tr069_token.h"
#include "tr069/tr069_store.h"
#include "tr069/tr069_index.h"

#define SDEBUG
#include "tr069/dm_assert.h"
#include "tr069/debug.h"

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include <net-snmp/library/snmp_assert.h>

#include "snmp_helper.h"
#include "radiusAuthServ.h"

#define radiusAuthServIdent_oid				1
#define radiusAuthServUpTime_oid			2
#define radiusAuthServResetTime_oid			3
#define radiusAuthServConfigReset_oid			4
#define radiusAuthServTotalAccessRequests_oid		5
#define radiusAuthServTotalInvalidRequests_oid		6
#define radiusAuthServTotalDupAccessRequests_oid	7
#define radiusAuthServTotalAccessAccepts_oid		8
#define radiusAuthServTotalAccessRejects_oid		9
#define radiusAuthServTotalAccessChallenges_oid		10
#define radiusAuthServTotalMalformedAccessRequests_oid	11
#define radiusAuthServTotalBadAuthenticators_oid	12
#define radiusAuthServTotalPacketsDropped_oid		13
#define radiusAuthServTotalUnknownTypes_oid		14
#define radiusAuthClientTable_oid			15
#define radiusAuthClientExtTable_oid			16

static oid radiusAuthServ_oid[] = { 1, 3, 6, 1, 2, 1, 67, 1, 1, 1, 1 };

static int
radiusAuthServ_handler(netsnmp_mib_handler *handler,
		       netsnmp_handler_registration *reginfo,
		       netsnmp_agent_request_info *reqinfo,
		       netsnmp_request_info *requests);

/** Initializes the radiusAuthServ module */
void
init_radiusAuthServ(void)
{
	netsnmp_handler_registration *reginfo;

	/*
	 * register ourselves with the agent as a group of scalars...
	 */
 
	DEBUGMSGTL(("radiusAuthServ", "Initializing\n"));

	reginfo = netsnmp_create_handler_registration("radiusAuthServ",
						      radiusAuthServ_handler,
						      radiusAuthServ_oid, OID_LENGTH(radiusAuthServ_oid),
						      HANDLER_CAN_RONLY);
	netsnmp_register_scalar_group(reginfo, radiusAuthServIdent_oid, radiusAuthClientExtTable_oid);
}

int
radiusAuthServ_handler(netsnmp_mib_handler *handler,
		       netsnmp_handler_registration *reginfo,
		       netsnmp_agent_request_info *reqinfo,
		       netsnmp_request_info *requests)
{
	struct tr069_value_table *globs;
	netsnmp_request_info  *request;
	netsnmp_variable_list *requestvb;
	unsigned int ret_value = 0;
	oid      subid;
	int      type;

	ENTER();

	/** VAR: InternetGatewayDevice.X_TPLINO_NET_SessionControl.RadiusServer.Authentication.Stats */
	globs = tr069_get_table_by_selector((tr069_selector){ cwmp__InternetGatewayDevice,
				cwmp__IGD_X_TPLINO_NET_SessionControl,
				cwmp__IGD_SCG_RadiusServer,
				cwmp__IGD_SCG_RS_Authentication,
				cwmp__IGD_SCG_RS_Auth_Stats, 0});
	/*
	 * 
	 *
	 */
	DEBUGMSGTL(("radiusAuthServ", "Handler - mode %s\n", se_find_label_in_slist("agent_mode", reqinfo->mode)));
	switch (reqinfo->mode) {
	case MODE_GET:
		for (request = requests; request; request = request->next) {
			requestvb = request->requestvb;
			subid = requestvb->name[OID_LENGTH(radiusAuthServ_oid)];  /* XXX */

			if (!globs) {
				netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHOBJECT);
				continue;
			}

			type = ASN_COUNTER;

			DEBUGMSGTL(( "radiusAuthServ", "oid: "));
			DEBUGMSGOID(("radiusAuthServ", requestvb->name, requestvb->name_length));
			DEBUGMSG((   "radiusAuthServ", "\n"));
			switch (subid) {
			case radiusAuthServIdent_oid:
				snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR, (unsigned char *)"", 0);
				continue;

			case radiusAuthServUpTime_oid:
			case radiusAuthServResetTime_oid:
				/* TODO: fill in sensible values */
				type = ASN_TIMETICKS;
				ret_value = 0;
				break;

			case radiusAuthServConfigReset_oid:
				type = ASN_INTEGER;
				ret_value = 4;
				break;

			case radiusAuthServTotalAccessRequests_oid:
				/** VAR: InternetGatewayDevice.X_TPLINO_NET_SessionControl.RadiusServer.Authentication.Stats.AccessRequests */
				ret_value = tr069_get_uint_by_id(globs, cwmp__IGD_SCG_RS_Auth_Stats_AccessRequests);
				break;

			case radiusAuthServTotalInvalidRequests_oid:
				/** VAR: InternetGatewayDevice.X_TPLINO_NET_SessionControl.RadiusServer.Authentication.Stats.InvalidRequests */
				ret_value = tr069_get_uint_by_id(globs, cwmp__IGD_SCG_RS_Auth_Stats_InvalidRequests);
				break;

			case radiusAuthServTotalDupAccessRequests_oid:
				/** VAR: InternetGatewayDevice.X_TPLINO_NET_SessionControl.RadiusServer.Authentication.Stats.DupAccessRequests */
				ret_value = tr069_get_uint_by_id(globs, cwmp__IGD_SCG_RS_Auth_Stats_DupAccessRequests);
				break;
				
			case radiusAuthServTotalAccessAccepts_oid:
				/** VAR: InternetGatewayDevice.X_TPLINO_NET_SessionControl.RadiusServer.Authentication.Stats.AccessAccepts */
				ret_value = tr069_get_uint_by_id(globs, cwmp__IGD_SCG_RS_Auth_Stats_AccessAccepts);
				break;

			case radiusAuthServTotalAccessRejects_oid:
				/** VAR: InternetGatewayDevice.X_TPLINO_NET_SessionControl.RadiusServer.Authentication.Stats.AccessRejects */
				ret_value = tr069_get_uint_by_id(globs, cwmp__IGD_SCG_RS_Auth_Stats_AccessRejects);
				break;

			case radiusAuthServTotalAccessChallenges_oid:
				/** VAR: InternetGatewayDevice.X_TPLINO_NET_SessionControl.RadiusServer.Authentication.Stats.AccessChallenges */
				ret_value = tr069_get_uint_by_id(globs, cwmp__IGD_SCG_RS_Auth_Stats_AccessChallenges);
				break;

			case radiusAuthServTotalMalformedAccessRequests_oid:
				/** VAR: InternetGatewayDevice.X_TPLINO_NET_SessionControl.RadiusServer.Authentication.Stats.MalformedRequests */
				ret_value = tr069_get_uint_by_id(globs, cwmp__IGD_SCG_RS_Auth_Stats_MalformedRequests);
				break;

			case radiusAuthServTotalBadAuthenticators_oid:
				/** VAR: InternetGatewayDevice.X_TPLINO_NET_SessionControl.RadiusServer.Authentication.Stats.BadAuthenticators */
				ret_value = tr069_get_uint_by_id(globs, cwmp__IGD_SCG_RS_Auth_Stats_BadAuthenticators);
				break;

			case radiusAuthServTotalPacketsDropped_oid:
				/** VAR: InternetGatewayDevice.X_TPLINO_NET_SessionControl.RadiusServer.Authentication.Stats.PacketsDropped */
				ret_value = tr069_get_uint_by_id(globs, cwmp__IGD_SCG_RS_Auth_Stats_PacketsDropped);
				break;

			case radiusAuthServTotalUnknownTypes_oid:
				/** VAR: InternetGatewayDevice.X_TPLINO_NET_SessionControl.RadiusServer.Authentication.Stats.UnknownTypes */
				ret_value = tr069_get_uint_by_id(globs, cwmp__IGD_SCG_RS_Auth_Stats_UnknownTypes);
				break;

			case radiusAuthClientTable_oid:
			case radiusAuthClientExtTable_oid:
				/*
				 * These are not actually valid scalar objects.
				 * The table registration should take precedence,
				 *   so skip thess subtree, regardless of architecture.
				 */
				netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHOBJECT);
				continue;
			}
			snmp_set_var_typed_value(request->requestvb, type, (u_char *)&ret_value, sizeof(ret_value));
		}
		break;

	case MODE_GETNEXT:
	case MODE_GETBULK:
	case MODE_SET_RESERVE1:
	case MODE_SET_RESERVE2:
	case MODE_SET_ACTION:
	case MODE_SET_COMMIT:
	case MODE_SET_FREE:
	case MODE_SET_UNDO:
		snmp_log(LOG_WARNING, "mibII/tcp: Unsupported mode (%d)\n", reqinfo->mode);
		break;
	default:
		snmp_log(LOG_WARNING, "mibII/tcp: Unrecognised mode (%d)\n", reqinfo->mode);
		break;
	}
	
	return SNMP_ERR_NOERROR;
}
