/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef RADIUSAUTHSERV_H
#define RADIUSAUTHSERV_H

/* function declarations */
void init_radiusAuthServ(void);

#endif /* RADIUSAUTHSERV_H */
