/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef RADIUSACCCLIENT_H
#define RADIUSACCCLIENT_H

/* function declarations */
void init_radiusAccClient(void);

#endif /* RADIUSACCCLIENT_H */
